#!/bin/sh
#
# Copyright (C) goblinhack@gmail.com
#
# This game is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This game is distributed in the hope that it will be fun,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this game; if not, write to the Free
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ./build/VERSION
. ./build/common.sh

echo ${RED}
echo "   ██████  ▄▄▄       ▄████▄   ██▀███  ▓█████  ▄████▄   ▄▄▄       ███▄    █ ▄▄▄█████▓"
echo " ▒██    ▒ ▒████▄    ▒██▀ ▀█  ▓██ ▒ ██▒▓█   ▀ ▒██▀ ▀█  ▒████▄     ██ ▀█   █ ▓  ██▒ ▓▒"
echo " ░ ▓██▄   ▒██  ▀█▄  ▒▓█    ▄ ▓██ ░▄█ ▒▒███   ▒▓█    ▄ ▒██  ▀█▄  ▓██  ▀█ ██▒▒ ▓██░ ▒░"
echo "   ▒   ██▒░██▄▄▄▄██ ▒▓▓▄ ▄██▒▒██▀▀█▄  ▒▓█  ▄ ▒▓▓▄ ▄██▒░██▄▄▄▄██ ▓██▒  ▐▌██▒░ ▓██▓ ░ "
echo " ▒██████▒▒ ▓█   ▓██▒▒ ▓███▀ ░░██▓ ▒██▒░▒████▒▒ ▓███▀ ░ ▓█   ▓██▒▒██░   ▓██░  ▒██▒ ░ "
echo " ▒ ▒▓▒ ▒ ░ ▒▒   ▓▒█░░ ░▒ ▒  ░░ ▒▓ ░▒▓░░░ ▒░ ░░ ░▒ ▒  ░ ▒▒   ▓▒█░░ ▒░   ▒ ▒   ▒ ░░   "
echo " ░ ░▒  ░ ░  ▒   ▒▒ ░  ░  ▒     ░▒ ░ ▒░ ░ ░  ░  ░  ▒     ▒   ▒▒ ░░ ░░   ░ ▒░    ░    "
echo " ░  ░  ░    ░   ▒   ░          ░░   ░    ░   ░          ░   ▒      ░   ░ ░   ░      "
echo "       ░        ░  ░░ ░         ░        ░  ░░ ░            ░  ░         ░          "
echo "                    ░                        ░                                      "
echo " "
echo ${RESET}

LOG=./build.log
MAINTAINER=goblinhack@gmail.com

tech_support()
{
    #
    # Record some useful to send back home on fail if we are permitted
    #
    (
        date

        log_info "DEBUG: System"
        echo =====================================================
        uname -a
        echo

        log_info "DEBUG: Environment"
        echo =====================================================
        env
        echo

        log_info "DEBUG: Installed packages"
        echo =====================================================
        (apt --installed list | grep -i SDL) 2>/dev/null
        (apt --installed list | grep gcc) 2>/dev/null
        (apt --installed list | grep clang) 2>/dev/null
        pacman -Q 2>/dev/null # msys2
        echo

        log_info "DEBUG: Installed compilers"
        echo =====================================================
        which clang++
        which clang
        which g++
        which gcc
        clang --version  2>/dev/null
        gcc --version  2>/dev/null
        /mingw64/bin/gcc.exe --version 2>/dev/null # msys2
        echo

        log_info "DEBUG: Make:"
        echo =====================================================
        set -x
        which make
        make --version
        set +x
        echo

        log_info "DEBUG: Makefile:"
        echo =====================================================
        cat Makefile
        echo

        log_info "DEBUG: src/Makefile:"
        echo =====================================================
        cat src/Makefile
        echo

    ) >> $LOG 2>&1
}

run() {
    STDOUT=$2
    EXIT_CODE=.exit_code
    ($1 2>&1; echo $? > $EXIT_CODE) | tee "$STDOUT"
    MY_RET="$(cat $EXIT_CODE)"
    /bin/rm $EXIT_CODE

    return "$MY_RET"
}

help()
{
    cat << %%
Build options:

Usage: $0 [options]

  [--rel]    Release build (all optimizations) (DEFAULT)
  [--dev]    Enable additional debugging
  [--sanity] Enable additional stack checking
  [--prof]   Enable gprof
  [--gcc]    Prefer g++ over clang
  [--github] CI/CD build (turns off modification of README)
%%
}

OPT_RELEASE_BUILD="yes"
OPT_DEBUG_BUILD=
OPT_SANITY_BUILD=
OPT_PROFILE_BUILD=
OPT_GCC=
OPT_GITHUB_BUILD=

read_opts()
{
    while [ "$#" -ne 0 ];
    do
        option=$1

        case $option in
            -*sanity)
                OPT_RELEASE_BUILD=
                OPT_SANITY_BUILD="yes"
                OPT_DEBUG_BUILD="yes"
                shift
                ;;
            -*dev)
                OPT_RELEASE_BUILD=
                OPT_SANITY_BUILD=
                OPT_DEBUG_BUILD="yes"
                shift
                ;;
            -*rel)
                OPT_DEBUG_BUILD=
                OPT_SANITY_BUILD=
                OPT_RELEASE_BUILD="yes"
                shift
                ;;
            -*prof)
                OPT_PROFILE_BUILD="yes"
                shift
                ;;
            -*gcc)
                OPT_GCC="yes"
                shift
                ;;
            -*clang)
                OPT_GCC=""
                shift
                ;;
            -*github)
                OPT_GITHUB_BUILD="yes"
                shift
                ;;
            *)

                log_err "Unknown argument: [$option]"
                help
                exit 1
                ;;
        esac
    done
}

export OPT_SANITY_BUILD
export OPT_DEBUG_BUILD
export OPT_RELEASE_BUILD
export OPT_GITHUB_BUILD
export OPT_PROFILE_BUILD
export OPT_GCC

read_opts "$@"

touch build/Makefile.template
make pre
run build/build.sh $LOG

if [ $? -ne 0 ]; then
    log_err "Build failed."
    log_info "Gathering tech support info to $LOG"
    tech_support >> $LOG
    log_err "Could you send $LOG to $MAINTAINER?"
    log_err "Or file an issue at https://github.com/goblinhack/sacrecant"
    exit 1
else
    #
    # For quick re-makes
    #
    ln -sf build/Makefile .
    log "Built successfully"
    rm $LOG
fi
