//
// Copyright goblinhack@gmail.com
//

#include "my_bpoint.hpp"
#include "my_callstack.hpp"
#include "my_level.hpp"
#include "my_level_ext.hpp"
#include "my_tp.hpp"
#include "my_types.hpp"

//
// Create all fixed levels
//
void levels_fixed(Gamep g)
{
  TRACE();

  {
    Overrides overrides;

    overrides[ 'B' ] = [](char /*c*/, bpoint /*p*/) -> Tpp { return tp_find_mand("boss1"); };

    level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_BOSS1, "boss1.1", __FUNCTION__, __LINE__, overrides, 0,
                    /* line */ (const char *) "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
                    /* line */ (const char *) "RRRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL,,RLLLLLLLLLLR",
                    /* line */ (const char *) "RRRLLLLLLLLLLLLLL,,,,,,,L,,,LLLLLL,,,LL,,LLLLLLR",
                    /* line */ (const char *) "RRLLLLLLLLLLLLL,,,,,,,,,L,,,,,,,,,,,,LL,,,LLLLLR",
                    /* line */ (const char *) "RRLLLL,,,,,,,,,,,,,,,,,,R,R,LRRRLL,,LLL,,,,LLLLR",
                    /* line */ (const char *) "RLLLL,,,,,,,LLLLLLLL,kLR=,,,LRLRRLL,LLL,,,,LLLLR",
                    /* line */ (const char *) "RLLL,,,,,,,,,LLLLLLLLLLR=RRRLLLLRLL,,LL,,,,LLLLR",
                    /* line */ (const char *) "RLL,,,,,,,R,,,LLRL,,,LLR=RL,LLLLLLL,,LLLLRLLLLLR",
                    /* line */ (const char *) "RLL,,,,,,R,,,,LRRL,,,L,,,LL,,,LLLLL,,,,,,,,,LLLR",
                    /* line */ (const char *) "RLL,,,,,R,,,,,RRRR,,,R,,,R,,,,LLLLL,,,,,,,,,,LLR",
                    /* line */ (const char *) "RLL,R,,,,,,,,,=======R,,,L,,..LLLLLL,,,L,LLL,,LR",
                    /* line */ (const char *) "RLL,,,,,,,,,,,RRRRRR=RLLLLL,,,,R,,,L,,,,,,,,,,LR",
                    /* line */ (const char *) "RLLL,,,,,,,,,LRLRRLR=RRL,L,,LLLL,,,R,,,,,LLL,,LR",
                    /* line */ (const char *) "RRLLL,,,,,,,LLLLLLLR=RLLLLLRLLLL,R,L,,,,,,,,,,LR",
                    /* line */ (const char *) "RRRLLL,,,,,LLRR,LLLR=RLL,,R,R,LL,,,L,,,,,,,,,LLR",
                    /* line */ (const char *) "RRRLLL,LLL,LLRR,LLRR=RR,,,,,,,,LLLLL,,,,,,,,LLLR",
                    /* line */ (const char *) "RRLLLLRLLL,LL,LLLLRR=R,,,,,,,,,LLLR,,,,LLLLLLLLR",
                    /* line */ (const char *) "RRLLR,,,,...,,,LLLLR=,,LLL,,,,,LLLR,,,,LLLLLLLLR",
                    /* line */ (const char *) "RRLL,,,,,.,,,,,,,,,,,,,LRL,,,R,LLL,,.,|L|L|L|LLR",
                    /* line */ (const char *) "RLLL,@,,,,,.,,B,R,,,R,,LLL,,,,,LLL,,,,=======ERR",
                    /* line */ (const char *) "RLLL,,,,..,.,,,LL,R,LL,,,,,,,,,,,,,,,L|L|L|L|RLR",
                    /* line */ (const char *) "RLLLLRLLLL,.,,,LL,,,LLLLLL,,,,,LL,,,,LLLLLLRRRLR",
                    /* line */ (const char *) "RLL,,,L,R,LL,,,LLRLRLLLLLLL,,,LLLL,,,,R,RLLRRRLR",
                    /* line */ (const char *) "RLL,,,LLLLLLLL,,,,,,RRLLLLLLRLLLLLR,,,,,,RLRRLLR",
                    /* line */ (const char *) "RL,,,,R,,,,,,,,,,,,,,,RR,,,,,,,LLLR,,,,,,LLL,,,R",
                    /* line */ (const char *) "RL,,,,,L,,,,,,,,,,,,,,,R,,,,,,,LLL,,,,,,,LLL,R,R",
                    /* line */ (const char *) "RLL,,,,L,,,,,,,,R,,,,,,,,,,,,,,,R,,L,L,L,LLLR,RR",
                    /* line */ (const char *) "RLLLLL,L,,,,,,,,,RR,,,,,,,,,,,,L,L,L,L.L,LLLLRLR",
                    /* line */ (const char *) "RRL,R,,R=RLL,,L,LLRLL,,,,,LLLLLL,L,L,LLL,LLLLLLR",
                    /* line */ (const char *) "RRLLLL,R=RL,,LLLLLLL,,,LLLLLLLLL,L,,,L,L,,LLLLLR",
                    /* line */ (const char *) "RLL,,,,,=,,,,LLLLLLLLLLLLLLLLLLL,L,L,L,L,LLLLLLR",
                    /* line */ (const char *) "RLL,,,,,=,,,,L,,,,,,,,LL,,,LR,,L,L,,,,,,,LLLLLLR",
                    /* line */ (const char *) "RLL,,,,,R,,,,R,,,,,LL,LLLLLL,,,L,LLLLL,LLLLLLLLR",
                    /* line */ (const char *) "RLLLRLLL,L,,,,,,,,LLL,LLLLLL,LRL,LLLLLRLLLLLLLLR",
                    /* line */ (const char *) "RL,,,LLL,,LLL,,,,,LL,,R,,,R,,RR,,,,,,,,,,,,,LLLR",
                    /* line */ (const char *) "RL,R,L,,,RLLL,,,,,,,,,L,L,,,,,,,,L,L,,,,,,,,,LLR",
                    /* line */ (const char *) "RL,,,R,L,RRRL,,RRRR,,,L,L,,,,,,,,,R,,,,R,,,,LLLR",
                    /* line */ (const char *) "RLL,LL,,,LLLR,RLLLLLLLL,L,,,,,,,,L,L,,,,,,,,LLLR",
                    /* line */ (const char *) "RLL,LL,,,LL,,,,,LLLLLLLLLLLLLLLL,,,,,,,,L,,LLRLR",
                    /* line */ (const char *) "RLL,L,,,,,L,L,,,,,LLLLLLLLRRLRLLLL,LLRLLLLLRRRRR",
                    /* line */ (const char *) "RRLLLLL,,,,,,,,,LLLLLLLLRRR,RRLLLLLL,,LLLLLLLLRR",
                    /* line */ (const char *) "RRLLLRRRLLL,,,,,LLLLLRRR,,LR,L,,,LLL,,LLL,,,LLRR",
                    /* line */ (const char *) "RRL,LRRRRRLLLLLLLRLRRR,,,,,,R,,,,,R,,,,R,,,,LRRR",
                    /* line */ (const char *) "RRR,LLR$$RLLLLLRR,,L,,,,,,,,R,,,,,L,,,,LL,,,LLRR",
                    /* line */ (const char *) "RRR,LRR$$RLLLLLL,,,LLLLL,,LLR,,L,,LL,,LLLLLLLLRR",
                    /* line */ (const char *) "RRR,LRL,,RLLLLLL,,RLLLLLLLLLLL,,,LLL,,LLLLLLLRRR",
                    /* line */ (const char *) "RRR,,,,,,,,,,,,,,,LLLLLLLLLLLLLLLLLLLLLLLLLRRRRR",
                    /* line */ (const char *) "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
                    /* end */ nullptr);

    level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_BOSS2, "boss2.1", __FUNCTION__, __LINE__, no_overrides, 0,
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x.@.E..........................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* end */ nullptr);

    level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_BOSS3, "boss3.1", __FUNCTION__, __LINE__, no_overrides, 0,
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x.@.E..........................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* end */ nullptr);

    level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_BOSS4, "boss4.1", __FUNCTION__, __LINE__, no_overrides, 0,
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x.@.E..........................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* end */ nullptr);

    level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_BOSS5, "boss5.1", __FUNCTION__, __LINE__, no_overrides, 0,
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x.@.E..........................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* end */ nullptr);
  }
}
