//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_charmap.hpp"
#include "my_level.hpp"

// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// 200 rooms of type 'cross' from seed 'maniac'
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
//
void rooms_cross(Gamep g)
{
  TRACE();

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^     ",
           /* line */ (const char *) "        .     ",
           /* line */ (const char *) "        .     ",
           /* line */ (const char *) "        .     ",
           /* line */ (const char *) "       ....   ",
           /* line */ (const char *) "  ........... ",
           /* line */ (const char *) "^............^",
           /* line */ (const char *) "  ........... ",
           /* line */ (const char *) "       ....   ",
           /* line */ (const char *) "       .      ",
           /* line */ (const char *) "       ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^  ",
           /* line */ (const char *) "^....... ",
           /* line */ (const char *) " ..g..g.^",
           /* line */ (const char *) "  ...... ",
           /* line */ (const char *) "     ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^              ",
           /* line */ (const char *) "   .              ",
           /* line */ (const char *) "  ............... ",
           /* line */ (const char *) "^...g..|..|..m.m.^",
           /* line */ (const char *) "  ............... ",
           /* line */ (const char *) "   ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^    ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) " ........^",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) "    ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^    ",
           /* line */ (const char *) "           .    ",
           /* line */ (const char *) "  ............  ",
           /* line */ (const char *) "^...........x.  ",
           /* line */ (const char *) "  ..g.g.m.x....^",
           /* line */ (const char *) "  ............  ",
           /* line */ (const char *) "            ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^           ",
           /* line */ (const char *) "       ...........^",
           /* line */ (const char *) "^...............   ",
           /* line */ (const char *) " ...............   ",
           /* line */ (const char *) "            ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^  ",
           /* line */ (const char *) "        ...  ",
           /* line */ (const char *) "        .|.  ",
           /* line */ (const char *) "        ...  ",
           /* line */ (const char *) "^........m.. ",
           /* line */ (const char *) "  ..x.x.....^",
           /* line */ (const char *) "  .......... ",
           /* line */ (const char *) "  .          ",
           /* line */ (const char *) "  ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^    ",
           /* line */ (const char *) "      .......^",
           /* line */ (const char *) "      ..|.|.. ",
           /* line */ (const char *) " ........m... ",
           /* line */ (const char *) "^.|.g.|.|.|.. ",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "         ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^       ",
           /* line */ (const char *) "         .....     ",
           /* line */ (const char *) "         ...|.     ",
           /* line */ (const char *) "         .g...     ",
           /* line */ (const char *) "^...........|.....^",
           /* line */ (const char *) " ................. ",
           /* line */ (const char *) "    ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^   ",
           /* line */ (const char *) "^.......... ",
           /* line */ (const char *) " ..g..g.m..^",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) "   ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                ^   ",
           /* line */ (const char *) "^.................  ",
           /* line */ (const char *) "  ..x.m...g.|......^",
           /* line */ (const char *) "  x.....x.....x.|.. ",
           /* line */ (const char *) "  xx........m...... ",
           /* line */ (const char *) "           ...   .m ",
           /* line */ (const char *) "            ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^                    ",
           /* line */ (const char *) "  ....................^",
           /* line */ (const char *) "^...................   ",
           /* line */ (const char *) "  ..................   ",
           /* line */ (const char *) "      .                ",
           /* line */ (const char *) "      ^                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^        ",
           /* line */ (const char *) "^.................^",
           /* line */ (const char *) " ....x.|.g.|...... ",
           /* line */ (const char *) "```..........m.G.. ",
           /* line */ (const char *) "````......x........",
           /* line */ (const char *) "C`       ....   ..m",
           /* line */ (const char *) "         ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "              ^       ",
           /* line */ (const char *) "  xx.................^",
           /* line */ (const char *) "  x....|.|..........  ",
           /* line */ (const char *) "  ..x......M..x..x..  ",
           /* line */ (const char *) "^........g..........  ",
           /* line */ (const char *) "        ......  ....  ",
           /* line */ (const char *) "            ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "              ^      ",
           /* line */ (const char *) "        .......      ",
           /* line */ (const char *) "        .....x.      ",
           /* line */ (const char *) "^........|.|........^",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "               ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^             ",
           /* line */ (const char *) " ..............  ",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) "       ......... ",
           /* line */ (const char *) "           ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^           ",
           /* line */ (const char *) "         ........     ",
           /* line */ (const char *) "         .LLL..g.     ",
           /* line */ (const char *) "  ........L|L........^",
           /* line */ (const char *) "^..x......LLL.m...... ",
           /* line */ (const char *) "  ...G..x........g... ",
           /* line */ (const char *) "  .................x. ",
           /* line */ (const char *) "    .            .... ",
           /* line */ (const char *) "    ^                 ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^        ",
           /* line */ (const char *) "     .......  ",
           /* line */ (const char *) "^.....m......^",
           /* line */ (const char *) " .......|.|.. ",
           /* line */ (const char *) "     .......  ",
           /* line */ (const char *) "          ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^            ",
           /* line */ (const char *) "    .            ",
           /* line */ (const char *) "    .........xx  ",
           /* line */ (const char *) "    ..g.vvv...x  ",
           /* line */ (const char *) "^.......smv.x...^",
           /* line */ (const char *) "   ...x.vvv....  ",
           /* line */ (const char *) "    ...........  ",
           /* line */ (const char *) "       ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^         ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) " ..x..g.|.^",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "^..g.x.g.. ",
           /* line */ (const char *) "  ........ ",
           /* line */ (const char *) "  ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^     ",
           /* line */ (const char *) "          .     ",
           /* line */ (const char *) "         ....   ",
           /* line */ (const char *) "         ......^",
           /* line */ (const char *) "   ......m.m.   ",
           /* line */ (const char *) "^....x.m.....   ",
           /* line */ (const char *) "   x.......```  ",
           /* line */ (const char *) "   xx.....````  ",
           /* line */ (const char *) "         .  `$  ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^       ",
           /* line */ (const char *) "^........... ",
           /* line */ (const char *) "  ..m.....g. ",
           /* line */ (const char *) "  ....xCx... ",
           /* line */ (const char *) "  ..x.C|C... ",
           /* line */ (const char *) "  x...xCx.|.^",
           /* line */ (const char *) "  xx........ ",
           /* line */ (const char *) "        .    ",
           /* line */ (const char *) "        ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) "     ........  ",
           /* line */ (const char *) "  ....vvv..m..^",
           /* line */ (const char *) "  ....sMv....  ",
           /* line */ (const char *) "  ..g.vvv..g.  ",
           /* line */ (const char *) "^............  ",
           /* line */ (const char *) "     ........  ",
           /* line */ (const char *) "      ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ~    ^~   ~",
           /* line */ (const char *) "     ~~ ~  ...~~~~~",
           /* line */ (const char *) "     ~~~~  .m. ~~~~",
           /* line */ (const char *) "    ~~ ~   ...~~~~ ",
           /* line */ (const char *) "    ~      .g.~~~  ",
           /* line */ (const char *) "^.................^",
           /* line */ (const char *) " ................. ",
           /* line */ (const char *) "       ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^       ",
           /* line */ (const char *) "  ..........^",
           /* line */ (const char *) "^...g.x.m.|. ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^           ",
           /* line */ (const char *) "      ..........  ",
           /* line */ (const char *) "      ....G.g.m.  ",
           /* line */ (const char *) "      ..g.......  ",
           /* line */ (const char *) "^.........g.|.|..^",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "          ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^        ",
           /* line */ (const char *) "   .....      ",
           /* line */ (const char *) "^............^",
           /* line */ (const char *) " .m.|.g..g.   ",
           /* line */ (const char *) " ..........   ",
           /* line */ (const char *) "         .    ",
           /* line */ (const char *) "         ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^      ",
           /* line */ (const char *) "     ......xx ",
           /* line */ (const char *) "^.....g..|..x ",
           /* line */ (const char *) "   .......... ",
           /* line */ (const char *) "   ..|.|.x.m.^",
           /* line */ (const char *) "   .......... ",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^  ",
           /* line */ (const char *) "     ....^",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) "  ....... ",
           /* line */ (const char *) "     .    ",
           /* line */ (const char *) "     ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "  ........... ",
           /* line */ (const char *) "^......x.|...^",
           /* line */ (const char *) "     .......  ",
           /* line */ (const char *) "          ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^          ",
           /* line */ (const char *) " ..........  ",
           /* line */ (const char *) "^...x.CCC...^",
           /* line */ (const char *) " .|...C$C....",
           /* line */ (const char *) " ...g.CCC.xx.",
           /* line */ (const char *) "  ........xx.",
           /* line */ (const char *) "       ^ ....",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^     ",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "^......|.x..g.g..^",
           /* line */ (const char *) "      ........... ",
           /* line */ (const char *) "      ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^   ",
           /* line */ (const char *) "^...........   ",
           /* line */ (const char *) " .M.|.........^",
           /* line */ (const char *) " .....|.x.m.m. ",
           /* line */ (const char *) "   ........... ",
           /* line */ (const char *) "          ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^        ",
           /* line */ (const char *) "      ..........  ",
           /* line */ (const char *) "      .|......g.  ",
           /* line */ (const char *) "      ...xxx....  ",
           /* line */ (const char *) "^........xxx..... ",
           /* line */ (const char *) " ......m.xxx..|..^",
           /* line */ (const char *) "      ..........  ",
           /* line */ (const char *) "            ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^        ",
           /* line */ (const char *) "     ........   ",
           /* line */ (const char *) " .......|.g.... ",
           /* line */ (const char *) "^.....g........^",
           /* line */ (const char *) "     ........   ",
           /* line */ (const char *) "            ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^    ",
           /* line */ (const char *) "             .    ",
           /* line */ (const char *) "       ........   ",
           /* line */ (const char *) "       .x...m..   ",
           /* line */ (const char *) "       ..x.....   ",
           /* line */ (const char *) "^.........x..m...^",
           /* line */ (const char *) "   .............  ",
           /* line */ (const char *) "            ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^     ",
           /* line */ (const char *) "   .  `m ",
           /* line */ (const char *) "   .```` ",
           /* line */ (const char *) "   ..``` ",
           /* line */ (const char *) "   ....  ",
           /* line */ (const char *) "^......  ",
           /* line */ (const char *) "  .x.x..^",
           /* line */ (const char *) "  .....  ",
           /* line */ (const char *) "    ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^     ",
           /* line */ (const char *) "  .     ",
           /* line */ (const char *) "  .     ",
           /* line */ (const char *) "  ....  ",
           /* line */ (const char *) "  ..|.  ",
           /* line */ (const char *) "^......^",
           /* line */ (const char *) " ..g..  ",
           /* line */ (const char *) " .....  ",
           /* line */ (const char *) "  ....  ",
           /* line */ (const char *) "   .    ",
           /* line */ (const char *) "   ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                  ^    ",
           /* line */ (const char *) "                  .    ",
           /* line */ (const char *) "  xx.................  ",
           /* line */ (const char *) "  x....m.m.g.G.......  ",
           /* line */ (const char *) "^...x...........m.g...^",
           /* line */ (const char *) "  ...................  ",
           /* line */ (const char *) "             ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^       ",
           /* line */ (const char *) " xxx............ ",
           /* line */ (const char *) " xxx..g..LL...x.^",
           /* line */ (const char *) " xx.....LLL..x.. ",
           /* line */ (const char *) "^.......LLm.x..x ",
           /* line */ (const char *) "      ........xx ",
           /* line */ (const char *) "           ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^       ",
           /* line */ (const char *) "          .       ",
           /* line */ (const char *) "      ..........  ",
           /* line */ (const char *) "   .............  ",
           /* line */ (const char *) "^................^",
           /* line */ (const char *) "   .............  ",
           /* line */ (const char *) "   .............  ",
           /* line */ (const char *) "      ..........  ",
           /* line */ (const char *) "        ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^            ",
           /* line */ (const char *) "^..................^",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) "        .......     ",
           /* line */ (const char *) "            ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^         ",
           /* line */ (const char *) "    .........^",
           /* line */ (const char *) "    .....m.M. ",
           /* line */ (const char *) "^.....m...... ",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "      ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "    ........ ",
           /* line */ (const char *) "    ..|.....^",
           /* line */ (const char *) "    .....x.. ",
           /* line */ (const char *) "^....x.|...x ",
           /* line */ (const char *) " .........xx ",
           /* line */ (const char *) "         ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^     ",
           /* line */ (const char *) "  ....... ",
           /* line */ (const char *) " ........^",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) "  ....... ",
           /* line */ (const char *) "  ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^     .$",
           /* line */ (const char *) " ..........|..",
           /* line */ (const char *) "^.G.x.......| ",
           /* line */ (const char *) " ......g.g...^",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "    ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^     ",
           /* line */ (const char *) "     ......     ",
           /* line */ (const char *) "^.......x.....  ",
           /* line */ (const char *) " .x.m.m....g...^",
           /* line */ (const char *) " .............  ",
           /* line */ (const char *) "        .       ",
           /* line */ (const char *) "        ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "     ..xx ",
           /* line */ (const char *) "     ...x ",
           /* line */ (const char *) "     ....^",
           /* line */ (const char *) "^......|. ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) "      ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^            ",
           /* line */ (const char *) "  ........xxx  ",
           /* line */ (const char *) "  .x....x...x  ",
           /* line */ (const char *) "  ....xxx.x.x  ",
           /* line */ (const char *) "  .|....x....  ",
           /* line */ (const char *) "^....m....|...^",
           /* line */ (const char *) " ............  ",
           /* line */ (const char *) "         .     ",
           /* line */ (const char *) "         .     ",
           /* line */ (const char *) "         ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "  ..x..CC.^",
           /* line */ (const char *) "  ....CCC. ",
           /* line */ (const char *) "^...x.CCm. ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "    ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^      ",
           /* line */ (const char *) "     .      ",
           /* line */ (const char *) "     ...... ",
           /* line */ (const char *) "     ...... ",
           /* line */ (const char *) "  .....xxx.^",
           /* line */ (const char *) "  ..|..xxx. ",
           /* line */ (const char *) "^......xxx. ",
           /* line */ (const char *) "  ......... ",
           /* line */ (const char *) "         .  ",
           /* line */ (const char *) "         .  ",
           /* line */ (const char *) "         ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^        ",
           /* line */ (const char *) "           ...       ",
           /* line */ (const char *) "           ...       ",
           /* line */ (const char *) "^...........x.......^",
           /* line */ (const char *) "   ...............   ",
           /* line */ (const char *) "           ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^   ",
           /* line */ (const char *) "       .   ",
           /* line */ (const char *) "     ....  ",
           /* line */ (const char *) "     .....^",
           /* line */ (const char *) "^........  ",
           /* line */ (const char *) "   ......  ",
           /* line */ (const char *) "     ....  ",
           /* line */ (const char *) "       .   ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^               ",
           /* line */ (const char *) "^.....................^",
           /* line */ (const char *) "  ..x....m..g.x.|...   ",
           /* line */ (const char *) "  x....m...........|   ",
           /* line */ (const char *) "  xx..........m...|..  ",
           /* line */ (const char *) "             ...   .$  ",
           /* line */ (const char *) "              ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "   ..x....^",
           /* line */ (const char *) "  ..xxx.g. ",
           /* line */ (const char *) "^....x.... ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                ^     ",
           /* line */ (const char *) "         .........    ",
           /* line */ (const char *) "         .LLm.x.x.    ",
           /* line */ (const char *) "         .LLL.....    ",
           /* line */ (const char *) "^..........LL.|.m....^",
           /* line */ (const char *) "   .................  ",
           /* line */ (const char *) "              .       ",
           /* line */ (const char *) "              ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^                ",
           /* line */ (const char *) "  ................... ",
           /* line */ (const char *) "^....................^",
           /* line */ (const char *) "  ................... ",
           /* line */ (const char *) "  ................... ",
           /* line */ (const char *) "          .......     ",
           /* line */ (const char *) "                ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^         ",
           /* line */ (const char *) "   ..............  ",
           /* line */ (const char *) "   ..............  ",
           /* line */ (const char *) "^.................^",
           /* line */ (const char *) "          .....    ",
           /* line */ (const char *) "           .       ",
           /* line */ (const char *) "           ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^     ",
           /* line */ (const char *) " ........^",
           /* line */ (const char *) "^..g..g.. ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) "    ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^      ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) " .x.x.g.. ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) "^.x.x.|..^",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) " .        ",
           /* line */ (const char *) " ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^          ",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "^.x.x....|.M.|.|. ",
           /* line */ (const char *) " ......x.........^",
           /* line */ (const char *) "      ........    ",
           /* line */ (const char *) "       ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^        ",
           /* line */ (const char *) " .      .m",
           /* line */ (const char *) " .........",
           /* line */ (const char *) " ........^",
           /* line */ (const char *) " ..|.m.|. ",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) "   ...... ",
           /* line */ (const char *) "       .  ",
           /* line */ (const char *) "       ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^     ",
           /* line */ (const char *) " .....   ",
           /* line */ (const char *) "^....... ",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) " .......^",
           /* line */ (const char *) "     ... ",
           /* line */ (const char *) "     ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^    ",
           /* line */ (const char *) "        .......   ",
           /* line */ (const char *) "        .m.x.|.   ",
           /* line */ (const char *) "^................^",
           /* line */ (const char *) " .x.|.x.m.x.|.x.. ",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "             ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^      ",
           /* line */ (const char *) "^.................^",
           /* line */ (const char *) "  ..|..g.x.|.|..   ",
           /* line */ (const char *) "  ..............   ",
           /* line */ (const char *) "  ^                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^         ",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) " .x..m.|.m......... ",
           /* line */ (const char *) "^...........x.m.g..^",
           /* line */ (const char *) "       ...........  ",
           /* line */ (const char *) "              ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^  ",
           /* line */ (const char *) "          .  ",
           /* line */ (const char *) "     .......^",
           /* line */ (const char *) "^......g.... ",
           /* line */ (const char *) "  .m.m....```",
           /* line */ (const char *) "  .......````",
           /* line */ (const char *) "       .   `m",
           /* line */ (const char *) "       ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^        ",
           /* line */ (const char *) " xxx.......... ",
           /* line */ (const char *) " xxx.x..mCC... ",
           /* line */ (const char *) " xx.....CCC.g. ",
           /* line */ (const char *) "^...x.x.CC....^",
           /* line */ (const char *) "   ........... ",
           /* line */ (const char *) "      ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^      ",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) "^.m..x..m.g.m.x.x..^",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) "        .......     ",
           /* line */ (const char *) "        ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^       ",
           /* line */ (const char *) "         .........^",
           /* line */ (const char *) "         .x.|...g. ",
           /* line */ (const char *) "   ...........m... ",
           /* line */ (const char *) "^..........m.....x ",
           /* line */ (const char *) "         .......xx ",
           /* line */ (const char *) "              ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^    ",
           /* line */ (const char *) "      .....  ",
           /* line */ (const char *) "^..........  ",
           /* line */ (const char *) " ...........^",
           /* line */ (const char *) " ..........  ",
           /* line */ (const char *) "       ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^  ",
           /* line */ (const char *) "     ....... ",
           /* line */ (const char *) "     .......^",
           /* line */ (const char *) "     ....... ",
           /* line */ (const char *) "^........... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "    ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "     ....... ",
           /* line */ (const char *) "     ...|...^",
           /* line */ (const char *) "^.....m...```",
           /* line */ (const char *) " ........````",
           /* line */ (const char *) "    ^      `C",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) " ...........^",
           /* line */ (const char *) "^..........  ",
           /* line */ (const char *) " ..........  ",
           /* line */ (const char *) "     ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^           ",
           /* line */ (const char *) "^............... ",
           /* line */ (const char *) " .g..g.m..|.x.g.^",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) "      ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^           ",
           /* line */ (const char *) "        .        `$ ",
           /* line */ (const char *) "^..............```` ",
           /* line */ (const char *) "   .g.M.....x...``` ",
           /* line */ (const char *) "   .....g.m........^",
           /* line */ (const char *) "   ...........m...  ",
           /* line */ (const char *) "        ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^               ",
           /* line */ (const char *) "        ........        ",
           /* line */ (const char *) "        ....xxx.        ",
           /* line */ (const char *) "        .m..x.x.        ",
           /* line */ (const char *) "^...........x.x.....    ",
           /* line */ (const char *) " .x.|..|..g.....m.M....^",
           /* line */ (const char *) " ...................    ",
           /* line */ (const char *) "        ^               ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^         ",
           /* line */ (const char *) "           .         ",
           /* line */ (const char *) "          ...        ",
           /* line */ (const char *) "          .|.        ",
           /* line */ (const char *) "          ...        ",
           /* line */ (const char *) " ..................  ",
           /* line */ (const char *) "^..g..x..x.g.g..m...^",
           /* line */ (const char *) " ..................  ",
           /* line */ (const char *) "              ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^       ",
           /* line */ (const char *) " .       ",
           /* line */ (const char *) " .....   ",
           /* line */ (const char *) "^.......^",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) " .       ",
           /* line */ (const char *) " ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^  ",
           /* line */ (const char *) "  ............ ",
           /* line */ (const char *) "  ............^",
           /* line */ (const char *) "^............. ",
           /* line */ (const char *) "  ............ ",
           /* line */ (const char *) "        .....  ",
           /* line */ (const char *) "            .  ",
           /* line */ (const char *) "            ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^              ",
           /* line */ (const char *) "   .          .m  ",
           /* line */ (const char *) "   ..........C..  ",
           /* line */ (const char *) "^.....x.|..g.CC   ",
           /* line */ (const char *) "  ```............^",
           /* line */ (const char *) "  ````....x....   ",
           /* line */ (const char *) "  C`     ...      ",
           /* line */ (const char *) "         .        ",
           /* line */ (const char *) "         ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^   ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "   .g...x. ",
           /* line */ (const char *) " ......x..^",
           /* line */ (const char *) "^.m.g.x..x ",
           /* line */ (const char *) " .......xx ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^      ",
           /* line */ (const char *) "        ......    ",
           /* line */ (const char *) "        ..LLL.    ",
           /* line */ (const char *) "  ........L|L....^",
           /* line */ (const char *) "^.........LLL.... ",
           /* line */ (const char *) "        ......    ",
           /* line */ (const char *) "             ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^          ",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "^..M.x...g.g. ",
           /* line */ (const char *) " ......g.....^",
           /* line */ (const char *) "  ........... ",
           /* line */ (const char *) "         ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "    ........ ",
           /* line */ (const char *) "^....x.x.xx.^",
           /* line */ (const char *) " xx......xx. ",
           /* line */ (const char *) " xxx.x.x.... ",
           /* line */ (const char *) " xxx........ ",
           /* line */ (const char *) "    ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^       ",
           /* line */ (const char *) "       .       ",
           /* line */ (const char *) "    .......xxx ",
           /* line */ (const char *) " ....|.|.|...x ",
           /* line */ (const char *) "^.xx..m....x.x ",
           /* line */ (const char *) " .xx.|.|.|....^",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) "    ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^           ",
           /* line */ (const char *) "         .........   ",
           /* line */ (const char *) "^..............x.... ",
           /* line */ (const char *) " .x..|.M.x.g.x...M..^",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "                 ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^         ",
           /* line */ (const char *) " .         ",
           /* line */ (const char *) " .......   ",
           /* line */ (const char *) "^.m.M.m...^",
           /* line */ (const char *) " .......   ",
           /* line */ (const char *) "    ....   ",
           /* line */ (const char *) "     .     ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) "        .      ",
           /* line */ (const char *) "      ........ ",
           /* line */ (const char *) " ......LLL.... ",
           /* line */ (const char *) " ......L|L..x. ",
           /* line */ (const char *) "^.|..|.LLL.... ",
           /* line */ (const char *) "............x.^",
           /* line */ (const char *) "m..   ........ ",
           /* line */ (const char *) "       ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^     ",
           /* line */ (const char *) " ......^",
           /* line */ (const char *) "^..|.m. ",
           /* line */ (const char *) " ...... ",
           /* line */ (const char *) "    ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^      ",
           /* line */ (const char *) "             .      ",
           /* line */ (const char *) "      ..........    ",
           /* line */ (const char *) " ......|.vvv..m....^",
           /* line */ (const char *) " .m.g....v$v....m.  ",
           /* line */ (const char *) "^......m.vvv.x....  ",
           /* line */ (const char *) "      ..........    ",
           /* line */ (const char *) "               ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^     ",
           /* line */ (const char *) "   .     ",
           /* line */ (const char *) "   .     ",
           /* line */ (const char *) "   .     ",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) " .......^",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) "^....... ",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) " .       ",
           /* line */ (const char *) " .       ",
           /* line */ (const char *) " ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^     ",
           /* line */ (const char *) "  ......^",
           /* line */ (const char *) "  ...... ",
           /* line */ (const char *) "^....... ",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) " ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^     ",
           /* line */ (const char *) " ...........  ",
           /* line */ (const char *) "^.x.vvv.|....^",
           /* line */ (const char *) " ...vTs...|.. ",
           /* line */ (const char *) " ...vvv.m.....",
           /* line */ (const char *) "  ............",
           /* line */ (const char *) "      ^     .m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ^   ",
           /* line */ (const char *) "               .   ",
           /* line */ (const char *) "        .........  ",
           /* line */ (const char *) "        ......|..  ",
           /* line */ (const char *) "^........x.m......^",
           /* line */ (const char *) "  ................ ",
           /* line */ (const char *) "        .          ",
           /* line */ (const char *) "        ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^            ",
           /* line */ (const char *) "^............... ",
           /* line */ (const char *) " ..m..x....x..x. ",
           /* line */ (const char *) " ........|......^",
           /* line */ (const char *) "      ......     ",
           /* line */ (const char *) "       ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^    ",
           /* line */ (const char *) "   .......  ",
           /* line */ (const char *) "^....m.....^",
           /* line */ (const char *) "  .....g..  ",
           /* line */ (const char *) "   .......  ",
           /* line */ (const char *) "       ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^            ",
           /* line */ (const char *) "^.................. ",
           /* line */ (const char *) "   ..|.m.g.....x.|.^",
           /* line */ (const char *) "   .........|...... ",
           /* line */ (const char *) "           ...      ",
           /* line */ (const char *) "             .      ",
           /* line */ (const char *) "             ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^    ",
           /* line */ (const char *) " xx........^",
           /* line */ (const char *) " x..x..x..  ",
           /* line */ (const char *) " ...x.....  ",
           /* line */ (const char *) " .xxx..x..  ",
           /* line */ (const char *) "^........x  ",
           /* line */ (const char *) " .......xx  ",
           /* line */ (const char *) "    ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^      ",
           /* line */ (const char *) "       ......   ",
           /* line */ (const char *) "       ..x.x.   ",
           /* line */ (const char *) "       ......   ",
           /* line */ (const char *) "^........x.x...^",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "          ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^             ",
           /* line */ (const char *) "^................. ",
           /* line */ (const char *) " ................. ",
           /* line */ (const char *) " .................^",
           /* line */ (const char *) "       ........    ",
           /* line */ (const char *) "            ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "      .    .m ",
           /* line */ (const char *) " xx.......... ",
           /* line */ (const char *) " x..x.|.|.... ",
           /* line */ (const char *) "^..x......g.  ",
           /* line */ (const char *) " .x....|.....^",
           /* line */ (const char *) " ....m.....|  ",
           /* line */ (const char *) " .........|.. ",
           /* line */ (const char *) "     ^     .$ ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "      ...... ",
           /* line */ (const char *) "   .......x. ",
           /* line */ (const char *) "^....x..m...^",
           /* line */ (const char *) "   .......m. ",
           /* line */ (const char *) "      ...... ",
           /* line */ (const char *) "          .  ",
           /* line */ (const char *) "          ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^   ",
           /* line */ (const char *) "            .   ",
           /* line */ (const char *) "          ...   ",
           /* line */ (const char *) "^..............^",
           /* line */ (const char *) " ...........x.. ",
           /* line */ (const char *) " CC.x.x.x.x...x ",
           /* line */ (const char *) "..C..........xx ",
           /* line */ (const char *) "m.    .         ",
           /* line */ (const char *) "      .         ",
           /* line */ (const char *) "      ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^       ",
           /* line */ (const char *) "      .......  ",
           /* line */ (const char *) "      ..x.g..  ",
           /* line */ (const char *) "^............. ",
           /* line */ (const char *) " .M.x.g....|.. ",
           /* line */ (const char *) " ........G....^",
           /* line */ (const char *) "      .......  ",
           /* line */ (const char *) "           ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^   ",
           /* line */ (const char *) "    ......^",
           /* line */ (const char *) "    ...... ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "^......... ",
           /* line */ (const char *) "    ...... ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^               ",
           /* line */ (const char *) "      .               ",
           /* line */ (const char *) "  ................xx  ",
           /* line */ (const char *) "^.........|..g.....x  ",
           /* line */ (const char *) "  .x.|.|.......m.x...^",
           /* line */ (const char *) "  ..................  ",
           /* line */ (const char *) "               .      ",
           /* line */ (const char *) "               ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "C``    ^        ",
           /* line */ (const char *) "```...........  ",
           /* line */ (const char *) " ``.m.CCC...m.. ",
           /* line */ (const char *) " `....C$C.x....^",
           /* line */ (const char *) "^.....CCC....|. ",
           /* line */ (const char *) "     .......... ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^  ",
           /* line */ (const char *) "        ......  ",
           /* line */ (const char *) "        ......  ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) " ..............^",
           /* line */ (const char *) "^.............. ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "            ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^          ",
           /* line */ (const char *) "^.........xx ",
           /* line */ (const char *) " .xx.|..x..x ",
           /* line */ (const char *) " .xx....x... ",
           /* line */ (const char *) " .......xxx.^",
           /* line */ (const char *) " .|.|.|..... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "    ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) "    ...     ",
           /* line */ (const char *) "    .|.     ",
           /* line */ (const char *) "  .....     ",
           /* line */ (const char *) "^..g.|.....^",
           /* line */ (const char *) "  .....     ",
           /* line */ (const char *) "    .       ",
           /* line */ (const char *) "    .       ",
           /* line */ (const char *) "    ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^             ",
           /* line */ (const char *) "^..............^",
           /* line */ (const char *) "  ..m.|.|.m.x.  ",
           /* line */ (const char *) "  ............  ",
           /* line */ (const char *) "        ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "       .     ",
           /* line */ (const char *) "    .......  ",
           /* line */ (const char *) "    .g...|.  ",
           /* line */ (const char *) "    ...g....^",
           /* line */ (const char *) "  .......x.  ",
           /* line */ (const char *) "^...m..g...  ",
           /* line */ (const char *) "  .........  ",
           /* line */ (const char *) "       ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^   ",
           /* line */ (const char *) "     .........  ",
           /* line */ (const char *) "     .m.|.....  ",
           /* line */ (const char *) "     ......g...^",
           /* line */ (const char *) " .......g.....  ",
           /* line */ (const char *) "^.|.x.g...|.x.  ",
           /* line */ (const char *) " .............  ",
           /* line */ (const char *) "           ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^        ",
           /* line */ (const char *) "       .........     ",
           /* line */ (const char *) "       .x.|.x.m.     ",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "^.......G.|.|.g.....^",
           /* line */ (const char *) "       .........     ",
           /* line */ (const char *) "               ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^        ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) " .........^",
           /* line */ (const char *) "^..g..m.m. ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) " ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^   ",
           /* line */ (const char *) "     ......   ",
           /* line */ (const char *) "     ......   ",
           /* line */ (const char *) "     .xxx..   ",
           /* line */ (const char *) " .....xxx....^",
           /* line */ (const char *) "^.|.|.xxx.|.  ",
           /* line */ (const char *) " ...........  ",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^     ",
           /* line */ (const char *) "             .     ",
           /* line */ (const char *) "           ...     ",
           /* line */ (const char *) "           .g.     ",
           /* line */ (const char *) "^.................^",
           /* line */ (const char *) "  ................ ",
           /* line */ (const char *) "      ^            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "   .......xx ",
           /* line */ (const char *) "   ..g..g..x ",
           /* line */ (const char *) " ...........^",
           /* line */ (const char *) "^.|......xx. ",
           /* line */ (const char *) " ...|.|..xx. ",
           /* line */ (const char *) "   ......... ",
           /* line */ (const char *) "          ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^    ",
           /* line */ (const char *) "       .    ",
           /* line */ (const char *) "       .    ",
           /* line */ (const char *) "       ...  ",
           /* line */ (const char *) "  .........^",
           /* line */ (const char *) "^.......x.. ",
           /* line */ (const char *) "  .G..G...x ",
           /* line */ (const char *) "  .......xx ",
           /* line */ (const char *) "     .      ",
           /* line */ (const char *) "     .      ",
           /* line */ (const char *) "     .      ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) " ........^",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) "     ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^       ",
           /* line */ (const char *) "^.....    ",
           /* line */ (const char *) " .....    ",
           /* line */ (const char *) " ..m..... ",
           /* line */ (const char *) " ....g.g.^",
           /* line */ (const char *) "   ...... ",
           /* line */ (const char *) "       ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) " ...x.m..^",
           /* line */ (const char *) "   ...... ",
           /* line */ (const char *) "    ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^       ",
           /* line */ (const char *) " ................. ",
           /* line */ (const char *) "^.x.x.x.....m..x..^",
           /* line */ (const char *) " .......g.m....... ",
           /* line */ (const char *) "       ......      ",
           /* line */ (const char *) "        ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ....^            ",
           /* line */ (const char *) " .............xx  ",
           /* line */ (const char *) " ..|.g.|.|.g...x  ",
           /* line */ (const char *) " ............m...^",
           /* line */ (const char *) "^..........|....  ",
           /* line */ (const char *) "         .....    ",
           /* line */ (const char *) "             ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^      ",
           /* line */ (const char *) "       ......    ",
           /* line */ (const char *) "^........m.g....^",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) "  ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ^    ",
           /* line */ (const char *) "       ..........   ",
           /* line */ (const char *) "       ...x..x.x.   ",
           /* line */ (const char *) "       ..xx...|..   ",
           /* line */ (const char *) " .......xxx..x.x..  ",
           /* line */ (const char *) "^..................^",
           /* line */ (const char *) "       ..........   ",
           /* line */ (const char *) "            ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^          ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "^...........^",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "    .......  ",
           /* line */ (const char *) "        ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) "    .       ",
           /* line */ (const char *) "^.....      ",
           /* line */ (const char *) "  .x....    ",
           /* line */ (const char *) "  ....m....^",
           /* line */ (const char *) "  ......    ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^          ",
           /* line */ (const char *) "   ...............  ",
           /* line */ (const char *) "^....x..x.m.|..x...^",
           /* line */ (const char *) "   ...............  ",
           /* line */ (const char *) "          ....      ",
           /* line */ (const char *) "            ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^       ",
           /* line */ (const char *) "         .       ",
           /* line */ (const char *) "         .       ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) "    .|..m.|.|..  ",
           /* line */ (const char *) "    ...........  ",
           /* line */ (const char *) "          ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^  ",
           /* line */ (const char *) "       ...  ",
           /* line */ (const char *) "^.......g..^",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) "       ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^        ",
           /* line */ (const char *) "    ...........  ",
           /* line */ (const char *) "^....x.g.x.|.x..^",
           /* line */ (const char *) " ..............  ",
           /* line */ (const char *) "     ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^       ",
           /* line */ (const char *) "     .       ",
           /* line */ (const char *) " .........   ",
           /* line */ (const char *) "^...........^",
           /* line */ (const char *) "   .......   ",
           /* line */ (const char *) "     .       ",
           /* line */ (const char *) "     .       ",
           /* line */ (const char *) "     ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                ^   ",
           /* line */ (const char *) "      ...........   ",
           /* line */ (const char *) "      ...........   ",
           /* line */ (const char *) "      ...........   ",
           /* line */ (const char *) "^.................. ",
           /* line */ (const char *) " ..................^",
           /* line */ (const char *) "      ...........   ",
           /* line */ (const char *) "           ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^      ",
           /* line */ (const char *) "         ...     ",
           /* line */ (const char *) "         ...     ",
           /* line */ (const char *) "^..........m....^",
           /* line */ (const char *) " .......x......  ",
           /* line */ (const char *) " ..x.g....x..``` ",
           /* line */ (const char *) " ...........```` ",
           /* line */ (const char *) "        .     `$ ",
           /* line */ (const char *) "        ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                 ^  ",
           /* line */ (const char *) "       ...........  ",
           /* line */ (const char *) "       .......m.|.  ",
           /* line */ (const char *) " ........|..m...... ",
           /* line */ (const char *) "^..x...m......x.m..^",
           /* line */ (const char *) " x...g...m.x....... ",
           /* line */ (const char *) " xx................ ",
           /* line */ (const char *) "            ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^           ",
           /* line */ (const char *) "      ........... ",
           /* line */ (const char *) " ........xxx...|.^",
           /* line */ (const char *) "^.x...m...mx.x... ",
           /* line */ (const char *) " ...x......x..... ",
           /* line */ (const char *) " ......m.G...m.m. ",
           /* line */ (const char *) "      ........... ",
           /* line */ (const char *) "             ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "  ......xx ",
           /* line */ (const char *) " ....m...x ",
           /* line */ (const char *) " .|....x.. ",
           /* line */ (const char *) "^...|.....^",
           /* line */ (const char *) " .....m.g. ",
           /* line */ (const char *) "  ........ ",
           /* line */ (const char *) "    ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^       ",
           /* line */ (const char *) "      .......... ",
           /* line */ (const char *) " ......xCx..|.|. ",
           /* line */ (const char *) " ..|.m.C|C......^",
           /* line */ (const char *) "^......xCx.m...x ",
           /* line */ (const char *) "      ........xx ",
           /* line */ (const char *) "             ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^        ",
           /* line */ (const char *) "     ......xx ",
           /* line */ (const char *) "     .vvv...x ",
           /* line */ (const char *) " .....smv.x.. ",
           /* line */ (const char *) " .....vvv.... ",
           /* line */ (const char *) "^..|.......g.^",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "      ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^  ",
           /* line */ (const char *) "   .....^",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) "^....... ",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) "      ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^        ",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) " ...m.... ",
           /* line */ (const char *) " .|....x. ",
           /* line */ (const char *) " ...M....^",
           /* line */ (const char *) " .|....|. ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) "       ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^         ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ..........^",
           /* line */ (const char *) "^.......... ",
           /* line */ (const char *) "   ........ ",
           /* line */ (const char *) "         ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^   ",
           /* line */ (const char *) "^........  ",
           /* line */ (const char *) " .....m...^",
           /* line */ (const char *) "     ....  ",
           /* line */ (const char *) "      ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) "      ...  ",
           /* line */ (const char *) "      ...  ",
           /* line */ (const char *) "      ...  ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) "      ...  ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^              ",
           /* line */ (const char *) "    ..................^",
           /* line */ (const char *) "^.....x.g..m..|.g..|.  ",
           /* line */ (const char *) "    .................  ",
           /* line */ (const char *) "            ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^            ",
           /* line */ (const char *) "  .................  ",
           /* line */ (const char *) "^.........m.m.m.....^",
           /* line */ (const char *) "         .......     ",
           /* line */ (const char *) "              ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) "        .      ",
           /* line */ (const char *) "^...........   ",
           /* line */ (const char *) "    ........   ",
           /* line */ (const char *) "    ..........^",
           /* line */ (const char *) "    ........   ",
           /* line */ (const char *) "      ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) " .........^",
           /* line */ (const char *) "^......... ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "      .... ",
           /* line */ (const char *) "      ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) "     ......... ",
           /* line */ (const char *) "     .........^",
           /* line */ (const char *) "^............. ",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) "            ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^   ",
           /* line */ (const char *) "      ...xx ",
           /* line */ (const char *) " .........x ",
           /* line */ (const char *) "^.......x..^",
           /* line */ (const char *) "      ..... ",
           /* line */ (const char *) "        ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^                ",
           /* line */ (const char *) "^...................^",
           /* line */ (const char *) "  .x.|.|.G..|..|.g.  ",
           /* line */ (const char *) "  .................  ",
           /* line */ (const char *) "            ...      ",
           /* line */ (const char *) "              ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        m.  ^~   ~ ",
           /* line */ (const char *) "   ~ ~  .....~~~~~ ",
           /* line */ (const char *) "    ~~  ..x.. ~~~~ ",
           /* line */ (const char *) "   ~~    ....~~~~  ",
           /* line */ (const char *) "         ....~~~   ",
           /* line */ (const char *) "^.........m.......^",
           /* line */ (const char *) " ................. ",
           /* line */ (const char *) "        ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                    ^     ",
           /* line */ (const char *) "                    .     ",
           /* line */ (const char *) "^.....................    ",
           /* line */ (const char *) "   .........m.M..g.......^",
           /* line */ (const char *) "          .........       ",
           /* line */ (const char *) "             ^            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^      ",
           /* line */ (const char *) "         ...      ",
           /* line */ (const char *) "         .|.      ",
           /* line */ (const char *) "^................^",
           /* line */ (const char *) "  .............   ",
           /* line */ (const char *) "       ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^          ",
           /* line */ (const char *) " ...............^",
           /* line */ (const char *) "^............... ",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) "     ........... ",
           /* line */ (const char *) "      ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^           ",
           /* line */ (const char *) "          .           ",
           /* line */ (const char *) "^...................  ",
           /* line */ (const char *) "  ...................^",
           /* line */ (const char *) "  ..................  ",
           /* line */ (const char *) "            ...       ",
           /* line */ (const char *) "            .         ",
           /* line */ (const char *) "            ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) " .........^",
           /* line */ (const char *) " .m..g.|.. ",
           /* line */ (const char *) "^......... ",
           /* line */ (const char *) "     ..... ",
           /* line */ (const char *) "        ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "      .       ",
           /* line */ (const char *) " ~ ~ ...xx ~~ ",
           /* line */ (const char *) "  ~  ....x  ~ ",
           /* line */ (const char *) " ~~  ..x.. ~ ~",
           /* line */ (const char *) "     .....    ",
           /* line */ (const char *) "^.....G.M...^ ",
           /* line */ (const char *) " ...........  ",
           /* line */ (const char *) "    ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "     ..... ",
           /* line */ (const char *) "     ..m.. ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "  ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^           ",
           /* line */ (const char *) "          .           ",
           /* line */ (const char *) "       ...........    ",
           /* line */ (const char *) "       ...x...x.|.    ",
           /* line */ (const char *) " ........m...m......  ",
           /* line */ (const char *) "^.G.m.|.x...x..|.|...^",
           /* line */ (const char *) " ...................  ",
           /* line */ (const char *) "        ^             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^        ",
           /* line */ (const char *) "    ........ ",
           /* line */ (const char *) "    ........^",
           /* line */ (const char *) "    ........ ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "^........... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "       ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                  ^  ",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) " ...................^",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "^................... ",
           /* line */ (const char *) "      ..........     ",
           /* line */ (const char *) "      ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ~~         ^    ~",
           /* line */ (const char *) "   ~~~  ....... ~ ~~",
           /* line */ (const char *) "   ~~~  .|..LL.~~~~ ",
           /* line */ (const char *) "    ~~~ ...LLL.~ ~~ ",
           /* line */ (const char *) "       ~.g.LLm.~    ",
           /* line */ (const char *) "^................^  ",
           /* line */ (const char *) " ................   ",
           /* line */ (const char *) "         ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "m`      ^         ",
           /* line */ (const char *) "````............. ",
           /* line */ (const char *) "```.......xCx..x. ",
           /* line */ (const char *) "^....m.g..C|C....^",
           /* line */ (const char *) " .........xCx.x.. ",
           /* line */ (const char *) "       .........  ",
           /* line */ (const char *) "             ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "      .....  ",
           /* line */ (const char *) "      .x.|.  ",
           /* line */ (const char *) "^...........^",
           /* line */ (const char *) "  .........  ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^    ",
           /* line */ (const char *) "^.............^",
           /* line */ (const char *) "    ..g.M.g.   ",
           /* line */ (const char *) "    ........   ",
           /* line */ (const char *) "          ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^         ",
           /* line */ (const char *) "           ...       ",
           /* line */ (const char *) "           ...       ",
           /* line */ (const char *) "^...........m.......^",
           /* line */ (const char *) "  .................. ",
           /* line */ (const char *) "  ^                  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^           ",
           /* line */ (const char *) "      ........    ",
           /* line */ (const char *) "      ..g.xxx.    ",
           /* line */ (const char *) "      ....xxx.    ",
           /* line */ (const char *) " .......m.xxx....^",
           /* line */ (const char *) "^.g.|.x........x. ",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "           ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^      ",
           /* line */ (const char *) "  ...........^",
           /* line */ (const char *) "  .....vvv.|. ",
           /* line */ (const char *) "  .vvv.sCv... ",
           /* line */ (const char *) " ..sTv.vvv... ",
           /* line */ (const char *) "^..vvv.....```",
           /* line */ (const char *) " .........````",
           /* line */ (const char *) "      ^     `m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^       ",
           /* line */ (const char *) "            .       ",
           /* line */ (const char *) "            .       ",
           /* line */ (const char *) "           .....    ",
           /* line */ (const char *) "^............x.....^",
           /* line */ (const char *) "   ..............   ",
           /* line */ (const char *) "      .             ",
           /* line */ (const char *) "      .             ",
           /* line */ (const char *) "      ^             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "              ^    ",
           /* line */ (const char *) "        .........  ",
           /* line */ (const char *) "        ...x.|...  ",
           /* line */ (const char *) "^........x.....g..^",
           /* line */ (const char *) " ................. ",
           /* line */ (const char *) "             ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "       ~ .   ",
           /* line */ (const char *) "    ~~ ~...  ",
           /* line */ (const char *) "    ~~~~...  ",
           /* line */ (const char *) "   ~~ ~ .g.  ",
           /* line */ (const char *) "   ~    ...  ",
           /* line */ (const char *) "^........x..^",
           /* line */ (const char *) "  .........  ",
           /* line */ (const char *) "     .       ",
           /* line */ (const char *) "     ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^       ",
           /* line */ (const char *) "       ....     ",
           /* line */ (const char *) "       ..m.     ",
           /* line */ (const char *) "^..............^",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "     ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "     .....   ",
           /* line */ (const char *) "  ..........^",
           /* line */ (const char *) "  .....m.m.  ",
           /* line */ (const char *) "  ..x......  ",
           /* line */ (const char *) "^......g...  ",
           /* line */ (const char *) "     .....   ",
           /* line */ (const char *) "        .    ",
           /* line */ (const char *) "        ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^     ",
           /* line */ (const char *) "            .     ",
           /* line */ (const char *) "            .     ",
           /* line */ (const char *) "         ....     ",
           /* line */ (const char *) "         ....     ",
           /* line */ (const char *) "         ....     ",
           /* line */ (const char *) "         ....     ",
           /* line */ (const char *) "^................^",
           /* line */ (const char *) "  ..............  ",
           /* line */ (const char *) "         .        ",
           /* line */ (const char *) "         ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "~~~      ^        ",
           /* line */ (const char *) " ~~~ ...........  ",
           /* line */ (const char *) " ~~~~..x.LL.....  ",
           /* line */ (const char *) " ~~~~....LLL.|..  ",
           /* line */ (const char *) "~~ ~~.g..mLL.....^",
           /* line */ (const char *) "^.............|.  ",
           /* line */ (const char *) " ...............  ",
           /* line */ (const char *) "  .               ",
           /* line */ (const char *) "  ^               ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "       .     ",
           /* line */ (const char *) "       .     ",
           /* line */ (const char *) "      ...    ",
           /* line */ (const char *) "      .G.    ",
           /* line */ (const char *) " ..........  ",
           /* line */ (const char *) "^......x....^",
           /* line */ (const char *) "      ...    ",
           /* line */ (const char *) "      .      ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^           ",
           /* line */ (const char *) "       .........      ",
           /* line */ (const char *) " ........m.|.........^",
           /* line */ (const char *) "^.m.|.x......x.m..    ",
           /* line */ (const char *) " .................    ",
           /* line */ (const char *) "  ^                   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^      ",
           /* line */ (const char *) "      .      ",
           /* line */ (const char *) " ...........^",
           /* line */ (const char *) " .x..|.|..   ",
           /* line */ (const char *) "^.....m...   ",
           /* line */ (const char *) " ....|.|..   ",
           /* line */ (const char *) "..m.......   ",
           /* line */ (const char *) "..........   ",
           /* line */ (const char *) "m.  ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^             ",
           /* line */ (const char *) "^.............    ",
           /* line */ (const char *) " .x..x..m..|.....^",
           /* line */ (const char *) " .............    ",
           /* line */ (const char *) "            .     ",
           /* line */ (const char *) "            ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^         ",
           /* line */ (const char *) "    ...........^",
           /* line */ (const char *) "    ..x.x..CCm. ",
           /* line */ (const char *) "    ...|...CCC. ",
           /* line */ (const char *) "^.....x.x...CC. ",
           /* line */ (const char *) " ...............",
           /* line */ (const char *) "         ^    .m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "  .......... ",
           /* line */ (const char *) " ..|........ ",
           /* line */ (const char *) "^....g.g.M.. ",
           /* line */ (const char *) " ..G........^",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "    ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^        ",
           /* line */ (const char *) "      .        ",
           /* line */ (const char *) "     ........  ",
           /* line */ (const char *) "    ..g..x....^",
           /* line */ (const char *) "^........xm..  ",
           /* line */ (const char *) "    |..g.xxx.  ",
           /* line */ (const char *) "   ..|.......  ",
           /* line */ (const char *) "   $.      ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^        ",
           /* line */ (const char *) "^...m......xx ",
           /* line */ (const char *) " `..........x ",
           /* line */ (const char *) " ``..g.m..|..^",
           /* line */ (const char *) "```.......... ",
           /* line */ (const char *) "$``  ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^          ",
           /* line */ (const char *) "         .          ",
           /* line */ (const char *) "         ....       ",
           /* line */ (const char *) "  ........m........ ",
           /* line */ (const char *) "^..................^",
           /* line */ (const char *) "         ....       ",
           /* line */ (const char *) "           ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^  ",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) " ..|..m.g.....^",
           /* line */ (const char *) "^..........|.. ",
           /* line */ (const char *) "     ........  ",
           /* line */ (const char *) "      ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^        .m",
           /* line */ (const char *) " .............",
           /* line */ (const char *) "^......m.g.|..",
           /* line */ (const char *) " x..m........^",
           /* line */ (const char *) " xx.......... ",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) " .........^",
           /* line */ (const char *) "^.xxx.x.x. ",
           /* line */ (const char *) " .xxx..... ",
           /* line */ (const char *) " .xxx.x.x..",
           /* line */ (const char *) " ..........",
           /* line */ (const char *) "    ^    .m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^         ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "   ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^         ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "^.......g..^",
           /* line */ (const char *) " x..g.M.... ",
           /* line */ (const char *) " xx......m. ",
           /* line */ (const char *) "      ......",
           /* line */ (const char *) "      ^   .m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^              ",
           /* line */ (const char *) "   ................^",
           /* line */ (const char *) "^...G..|.x....x.|.  ",
           /* line */ (const char *) "   ........|......  ",
           /* line */ (const char *) "        .........   ",
           /* line */ (const char *) "            ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^       ",
           /* line */ (const char *) "^.........   ",
           /* line */ (const char *) "  .g.LLm....^",
           /* line */ (const char *) "  ...LLL..m. ",
           /* line */ (const char *) "  ....LL.... ",
           /* line */ (const char *) "    ........ ",
           /* line */ (const char *) "          .  ",
           /* line */ (const char *) "          .  ",
           /* line */ (const char *) "          ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^         ",
           /* line */ (const char *) "^.........   ",
           /* line */ (const char *) "  ..|.x.|..  ",
           /* line */ (const char *) "  ..........^",
           /* line */ (const char *) "        ...  ",
           /* line */ (const char *) "         .   ",
           /* line */ (const char *) "         ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^        ",
           /* line */ (const char *) "       ........    ",
           /* line */ (const char *) "       .|...xx.    ",
           /* line */ (const char *) " ..........xxx.... ",
           /* line */ (const char *) " ..m.x.g.M.xx..|.. ",
           /* line */ (const char *) "^.................^",
           /* line */ (const char *) "       ........    ",
           /* line */ (const char *) "          ^        ",
           /* end */ nullptr);

}
