//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_level.hpp"

//
// Create all prefab rooms
//
void rooms_prefab_locked(Gamep g)
{
  TRACE();

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) " x....+^",
           /* line */ (const char *) " x$...x ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxxx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) " xxx....xxx ",
           /* line */ (const char *) " x$s......x ",
           /* line */ (const char *) " xxx....xxx ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xxx.xx   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   xxxxxx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) " xxx....xxx ",
           /* line */ (const char *) " x.s....s$x ",
           /* line */ (const char *) " xxxB..Bxxx ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xxx.xx   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxxxx   ",
           /* line */ (const char *) "   x$$...x   ",
           /* line */ (const char *) "   xxxxxsx   ",
           /* line */ (const char *) "   xB...Bx   ",
           /* line */ (const char *) " xxx.....xxx ",
           /* line */ (const char *) " x.........x ",
           /* line */ (const char *) " xxxB...Bxxx ",
           /* line */ (const char *) "   x.....x   ",
           /* line */ (const char *) "   xB...Bx   ",
           /* line */ (const char *) "   x.....x   ",
           /* line */ (const char *) "   xB...Bx   ",
           /* line */ (const char *) "   x.....x   ",
           /* line */ (const char *) "   xxx.xxx   ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   xxxxxx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) " xxx....xxx ",
           /* line */ (const char *) " x$s....s$x ",
           /* line */ (const char *) " xxxB..Bxxx ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xxx+xx   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   xxxxxxxxx",
           /* line */ (const char *) "   x....s$$x",
           /* line */ (const char *) "   xB..Bxxxx",
           /* line */ (const char *) " xxx....xxx ",
           /* line */ (const char *) " x...M....x ",
           /* line */ (const char *) " xxxB..Bxxx ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x$..$x   ",
           /* line */ (const char *) "   xx+xxx   ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   xxxxxxxxx",
           /* line */ (const char *) "   x....s.bx",
           /* line */ (const char *) "   x....xb$x",
           /* line */ (const char *) "   x....xxxx",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "xxxx....xxxx",
           /* line */ (const char *) "x..........x",
           /* line */ (const char *) "x..........x",
           /* line */ (const char *) "xxxxB..Bxxxx",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xx+xxx   ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   xxxxxx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "xxxx....xxxx",
           /* line */ (const char *) "x$$s.......x",
           /* line */ (const char *) "x$$x.......x",
           /* line */ (const char *) "xxxxB..Bxxxx",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xB..Bx   ",
           /* line */ (const char *) "   x....x   ",
           /* line */ (const char *) "   xx+xxx   ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ",
           /* line */ (const char *) "   xxxxxx    ",
           /* line */ (const char *) "   x....+...^",
           /* line */ (const char *) "   xB..Bx    ",
           /* line */ (const char *) "xxxx....xxxx ",
           /* line */ (const char *) "x$.C....CM.x ",
           /* line */ (const char *) "x$.C....C..x ",
           /* line */ (const char *) "xxxxxxxxxxxx ",
           /* line */ (const char *) "             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ",
           /* line */ (const char *) "   xxxxxx    ",
           /* line */ (const char *) "   x....+...^",
           /* line */ (const char *) "   xB..Bx    ",
           /* line */ (const char *) "xxxx....xxxx ",
           /* line */ (const char *) "x..CCCCCC..x ",
           /* line */ (const char *) "x..C....CM.x ",
           /* line */ (const char *) "x..C....C..x ",
           /* line */ (const char *) "x$.C....C..x ",
           /* line */ (const char *) "x$.CCCCCC..x ",
           /* line */ (const char *) "xxxxxxxxxxxx ",
           /* line */ (const char *) "             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) " x....+^",
           /* line */ (const char *) " x$..$x ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) " x$`..+^",
           /* line */ (const char *) " x$``.x ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) "xxxxxxx ",
           /* line */ (const char *) "x.s...+^",
           /* line */ (const char *) "x.x...x^",
           /* line */ (const char *) "x.xxxxx ",
           /* line */ (const char *) "x.`$$$x ",
           /* line */ (const char *) "xxxxxxx ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) " x....+^",
           /* line */ (const char *) " x....x ",
           /* line */ (const char *) " x$...x ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) " x....+^",
           /* line */ (const char *) " x..m.x ",
           /* line */ (const char *) " x....x ",
           /* line */ (const char *) " x$...x ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) " x....+^",
           /* line */ (const char *) " x....x ",
           /* line */ (const char *) " x....x ",
           /* line */ (const char *) " x....x ",
           /* line */ (const char *) " x$..Mx ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) " xM...x ",
           /* line */ (const char *) " x.$..x ",
           /* line */ (const char *) " x..$.+^",
           /* line */ (const char *) " xm...x ",
           /* line */ (const char *) " xxxxxx ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ",
           /* line */ (const char *) " xxxxxx    ",
           /* line */ (const char *) " x....xxxx ",
           /* line */ (const char *) " x.$.....x ",
           /* line */ (const char *) " x..$....+^",
           /* line */ (const char *) " xM......x ",
           /* line */ (const char *) " xxxxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) " xxxxxx     ",
           /* line */ (const char *) " x....x     ",
           /* line */ (const char *) " x.$..xxxx  ",
           /* line */ (const char *) " x..$....+.^",
           /* line */ (const char *) " xM......x  ",
           /* line */ (const char *) " xxxxxxxxx  ",
           /* line */ (const char *) "            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) " xxxxxx     ",
           /* line */ (const char *) " x....x     ",
           /* line */ (const char *) " x.$..xxxx  ",
           /* line */ (const char *) " x..$....+.^",
           /* line */ (const char *) " xG...xxxx  ",
           /* line */ (const char *) " x....x     ",
           /* line */ (const char *) " xxxxxx     ",
           /* line */ (const char *) "            ",
           /* line */ (const char *) "            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ",
           /* line */ (const char *) " xxxxxx        ",
           /* line */ (const char *) " x....x        ",
           /* line */ (const char *) " x.$..xxxxxxxx ",
           /* line */ (const char *) " x..$........+^",
           /* line */ (const char *) " xG...xxxxxxxx ",
           /* line */ (const char *) " x....x        ",
           /* line */ (const char *) " xxxxxx        ",
           /* line */ (const char *) "               ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ",
           /* line */ (const char *) " xxxxxx        ",
           /* line */ (const char *) " x....x        ",
           /* line */ (const char *) " x.$..xxxxxxxx ",
           /* line */ (const char *) " x..$....CC..+^",
           /* line */ (const char *) " xM...xxxxxxxx ",
           /* line */ (const char *) " x....x        ",
           /* line */ (const char *) " x....x        ",
           /* line */ (const char *) " x....x        ",
           /* line */ (const char *) " xxxxxx        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^    ",
           /* line */ (const char *) "^......... ",
           /* line */ (const char *) " .xxxxxxx.^",
           /* line */ (const char *) " .+.B.B.x. ",
           /* line */ (const char *) " .x..$..x. ",
           /* line */ (const char *) " .x.B.B.x. ",
           /* line */ (const char *) " .xxxxxxx. ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "        ^  ",
           /* end */ nullptr);
}
