//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_charmap.hpp"
#include "my_level.hpp"

// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// 100 rooms of type 'cross' from seed 'maniac'
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
//
void rooms_cross(Gamep g)
{
  TRACE();

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^        ",
           /* line */ (const char *) "^.......... ",
           /* line */ (const char *) "...x.|.x.|.^",
           /* line */ (const char *) ".m......... ",
           /* line */ (const char *) "........... ",
           /* line */ (const char *) "....   ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^  ",
           /* line */ (const char *) "    ........... ",
           /* line */ (const char *) " ..............^",
           /* line */ (const char *) "^.............. ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^          ",
           /* line */ (const char *) "         ....       ",
           /* line */ (const char *) "         .g..       ",
           /* line */ (const char *) "^..................^",
           /* line */ (const char *) "  xx...G..m.|.x...  ",
           /* line */ (const char *) "  xxx...........``` ",
           /* line */ (const char *) "  xxx..........```` ",
           /* line */ (const char *) "        ^        `C ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^  ",
           /* line */ (const char *) "^........... ",
           /* line */ (const char *) " .x...x...x.^",
           /* line */ (const char *) " ...m...g... ",
           /* line */ (const char *) " .....g..... ",
           /* line */ (const char *) "    ......   ",
           /* line */ (const char *) "        ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^         ",
           /* line */ (const char *) "   ......... ",
           /* line */ (const char *) "   .g..m.... ",
           /* line */ (const char *) "^.........x.^",
           /* line */ (const char *) " ..x.....x.. ",
           /* line */ (const char *) " ....|..x..x ",
           /* line */ (const char *) "   .......xx ",
           /* line */ (const char *) "     ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^  ",
           /* line */ (const char *) "^.........  ",
           /* line */ (const char *) " .m.m.|.... ",
           /* line */ (const char *) " .......|..^",
           /* line */ (const char *) "   ........ ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^          ",
           /* line */ (const char *) "       ...........^",
           /* line */ (const char *) "^.......vvv..|.x.. ",
           /* line */ (const char *) " ..m.x..v$v....... ",
           /* line */ (const char *) " .......vvv.|.M.x. ",
           /* line */ (const char *) "       ........... ",
           /* line */ (const char *) "          ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^   ",
           /* line */ (const char *) "       .   ",
           /* line */ (const char *) " ........  ",
           /* line */ (const char *) "^.|.|..x.  ",
           /* line */ (const char *) " .....x...^",
           /* line */ (const char *) " .m..x..x  ",
           /* line */ (const char *) ".......xx  ",
           /* line */ (const char *) "m.  .      ",
           /* line */ (const char *) "    ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^         ",
           /* line */ (const char *) "  xxxxx      .        ~",
           /* line */ (const char *) "  xm~$x..........  ~~ ~",
           /* line */ (const char *) "  x~~~x.x..xxx.|.  ~~~~",
           /* line */ (const char *) "  xT~~x.....mx... ~~ ~ ",
           /* line */ (const char *) "  xxxxx.m.g..x.g. ~    ",
           /* line */ (const char *) "^...................^  ",
           /* line */ (const char *) "   .................   ",
           /* line */ (const char *) "   .                   ",
           /* line */ (const char *) "   .                   ",
           /* line */ (const char *) "   ^                   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "  xx........  ",
           /* line */ (const char *) "  x...g......^",
           /* line */ (const char *) "^...x....x.x  ",
           /* line */ (const char *) "  ....|....x  ",
           /* line */ (const char *) "    .....xxx  ",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^     ",
           /* line */ (const char *) "  ........... ",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "^............ ",
           /* line */ (const char *) " ............^",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "  ........... ",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^   ",
           /* line */ (const char *) "   .... ",
           /* line */ (const char *) "   .... ",
           /* line */ (const char *) "^...... ",
           /* line */ (const char *) " ......^",
           /* line */ (const char *) " ...... ",
           /* line */ (const char *) "    ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^      ",
           /* line */ (const char *) "         .....      ",
           /* line */ (const char *) "         .m.|.      ",
           /* line */ (const char *) "^..................^",
           /* line */ (const char *) " .........|.g...... ",
           /* line */ (const char *) "         .....      ",
           /* line */ (const char *) "            ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ^     ",
           /* line */ (const char *) "           .....     ",
           /* line */ (const char *) "           .....     ",
           /* line */ (const char *) "           .mCC.     ",
           /* line */ (const char *) "^...........CCC..... ",
           /* line */ (const char *) " ...........CC......^",
           /* line */ (const char *) "           .....     ",
           /* line */ (const char *) "           ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^    ",
           /* line */ (const char *) "  .......... ",
           /* line */ (const char *) "  .......... ",
           /* line */ (const char *) "  ..........^",
           /* line */ (const char *) "  .......... ",
           /* line */ (const char *) "^........... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "        ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^   ",
           /* line */ (const char *) "    ....... ",
           /* line */ (const char *) "    ..vsv.. ",
           /* line */ (const char *) "    ..vmv..^",
           /* line */ (const char *) "^.....vvv.. ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "      .   ",
           /* line */ (const char *) "      .   ",
           /* line */ (const char *) "     .... ",
           /* line */ (const char *) "     .... ",
           /* line */ (const char *) "     ....^",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) "     .... ",
           /* line */ (const char *) "      .   ",
           /* line */ (const char *) "      ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^    ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "^...........^",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "  .......... ",
           /* line */ (const char *) "     ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^   ",
           /* line */ (const char *) "         ...   ",
           /* line */ (const char *) "         ...   ",
           /* line */ (const char *) "^.........x... ",
           /* line */ (const char *) " ...m...m.....^",
           /* line */ (const char *) " .m...g....|.. ",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) " ^             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "   .........^",
           /* line */ (const char *) "^........... ",
           /* line */ (const char *) "   ......... ",
           /* line */ (const char *) "         ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^             ",
           /* line */ (const char *) " ..................^",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) "^.................. ",
           /* line */ (const char *) "      ...........   ",
           /* line */ (const char *) "          ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^    ",
           /* line */ (const char *) "      ...  ",
           /* line */ (const char *) "^......g.. ",
           /* line */ (const char *) " ..|.x.... ",
           /* line */ (const char *) " ......g..^",
           /* line */ (const char *) "      ...  ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^     ",
           /* line */ (const char *) "    .     ",
           /* line */ (const char *) "^......   ",
           /* line */ (const char *) " ...g....^",
           /* line */ (const char *) "   ....   ",
           /* line */ (const char *) "   .      ",
           /* line */ (const char *) "   .      ",
           /* line */ (const char *) "   ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^       ",
           /* line */ (const char *) "     ........   ",
           /* line */ (const char *) "     .g.m.g..   ",
           /* line */ (const char *) " .............  ",
           /* line */ (const char *) "^......|.x.|...^",
           /* line */ (const char *) "     ........   ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^       ",
           /* line */ (const char *) "       .....     ",
           /* line */ (const char *) "       .....     ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) "       .....     ",
           /* line */ (const char *) "        ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^     ",
           /* line */ (const char *) " ....  ",
           /* line */ (const char *) " .....^",
           /* line */ (const char *) "^..... ",
           /* line */ (const char *) "  .... ",
           /* line */ (const char *) "   ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^     ",
           /* line */ (const char *) "        .....   ",
           /* line */ (const char *) " ..............^",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "^.............. ",
           /* line */ (const char *) "        .....   ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "m`` ^  .$",
           /* line */ (const char *) "```...|..",
           /* line */ (const char *) " ``.m..| ",
           /* line */ (const char *) " `......^",
           /* line */ (const char *) "^....g.. ",
           /* line */ (const char *) "    .... ",
           /* line */ (const char *) "     ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "    .........^",
           /* line */ (const char *) "  ...g......  ",
           /* line */ (const char *) "  ......xx..  ",
           /* line */ (const char *) "  ..g..xxx..  ",
           /* line */ (const char *) "^......xx...  ",
           /* line */ (const char *) "    ........  ",
           /* line */ (const char *) "       ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^         ",
           /* line */ (const char *) " .........    ",
           /* line */ (const char *) "^.........    ",
           /* line */ (const char *) " ............^",
           /* line */ (const char *) " .........    ",
           /* line */ (const char *) " .........    ",
           /* line */ (const char *) "      .       ",
           /* line */ (const char *) "      .       ",
           /* line */ (const char *) "      ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^   ",
           /* line */ (const char *) "     .......  ",
           /* line */ (const char *) "^............^",
           /* line */ (const char *) "  ..........  ",
           /* line */ (const char *) "        .     ",
           /* line */ (const char *) "        ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^         ",
           /* line */ (const char *) "     .........  ",
           /* line */ (const char *) "     ...|.xxx.  ",
           /* line */ (const char *) "   ...x...xxx.  ",
           /* line */ (const char *) "^...m.xxx.xxx..^",
           /* line */ (const char *) "   .....x.....  ",
           /* line */ (const char *) "     .........  ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^            ",
           /* line */ (const char *) "     .            ",
           /* line */ (const char *) "  .............   ",
           /* line */ (const char *) "^.....m.|..x.....^",
           /* line */ (const char *) "     ........     ",
           /* line */ (const char *) "            .     ",
           /* line */ (const char *) "            ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^    ",
           /* line */ (const char *) "      ...... ",
           /* line */ (const char *) "      ...... ",
           /* line */ (const char *) "^........... ",
           /* line */ (const char *) "    ........^",
           /* line */ (const char *) "      ...... ",
           /* line */ (const char *) "        ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^                 ",
           /* line */ (const char *) "^...................  ",
           /* line */ (const char *) ".........|..x....x...^",
           /* line */ (const char *) ".g.x.x.M.......m...x  ",
           /* line */ (const char *) "...........|.|....xx  ",
           /* line */ (const char *) "....      .....       ",
           /* line */ (const char *) "          ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^          ",
           /* line */ (const char *) "      .          ",
           /* line */ (const char *) "    ............^",
           /* line */ (const char *) "    ..x.|..xx.   ",
           /* line */ (const char *) "    .......xx.   ",
           /* line */ (const char *) "^....|.x......   ",
           /* line */ (const char *) "  .g.....x..|.   ",
           /* line */ (const char *) "  ............   ",
           /* line */ (const char *) "         ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^       ",
           /* line */ (const char *) "        ....    ",
           /* line */ (const char *) "  ........g.    ",
           /* line */ (const char *) "  .g.x..g......^",
           /* line */ (const char *) "^..........x    ",
           /* line */ (const char *) "        ..xx    ",
           /* line */ (const char *) "         .      ",
           /* line */ (const char *) "         .      ",
           /* line */ (const char *) "         .      ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^          ",
           /* line */ (const char *) "^..........   ",
           /* line */ (const char *) " ..m...g.....^",
           /* line */ (const char *) " ....x...|..  ",
           /* line */ (const char *) " ..g........  ",
           /* line */ (const char *) " ....  .      ",
           /* line */ (const char *) "       ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^     ",
           /* line */ (const char *) "        ...   ",
           /* line */ (const char *) "^............ ",
           /* line */ (const char *) " .g.m.g.m.g..^",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^        ",
           /* line */ (const char *) " ..............   ",
           /* line */ (const char *) " .|.....x.|....   ",
           /* line */ (const char *) "^...|.m.....m....^",
           /* line */ (const char *) " .......|.|...g.  ",
           /* line */ (const char *) "     ...........  ",
           /* line */ (const char *) "       .          ",
           /* line */ (const char *) "       ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^       ",
           /* line */ (const char *) "     ......... ",
           /* line */ (const char *) "     ..xxx.x.. ",
           /* line */ (const char *) " ......xxx.... ",
           /* line */ (const char *) "^......xxx.g..^",
           /* line */ (const char *) " x..|........x ",
           /* line */ (const char *) " xx.........xx ",
           /* line */ (const char *) "           .   ",
           /* line */ (const char *) "           ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^   ",
           /* line */ (const char *) "   .... ",
           /* line */ (const char *) "   .g.. ",
           /* line */ (const char *) " ......^",
           /* line */ (const char *) " .m.x.. ",
           /* line */ (const char *) "^.....x ",
           /* line */ (const char *) " ....xx ",
           /* line */ (const char *) " ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^   ",
           /* line */ (const char *) "^.....  ",
           /* line */ (const char *) " ......^",
           /* line */ (const char *) " ...... ",
           /* line */ (const char *) " ...... ",
           /* line */ (const char *) " ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^    ",
           /* line */ (const char *) "    ........^",
           /* line */ (const char *) "^....x..CCm. ",
           /* line */ (const char *) " ..g....CCC. ",
           /* line */ (const char *) " ....|...CC. ",
           /* line */ (const char *) "    ........ ",
           /* line */ (const char *) "     ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^     ",
           /* line */ (const char *) "  ...xx ",
           /* line */ (const char *) "  ....x ",
           /* line */ (const char *) "  ..x..^",
           /* line */ (const char *) " ...... ",
           /* line */ (const char *) "^.m..|. ",
           /* line */ (const char *) " ...... ",
           /* line */ (const char *) " ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^    ",
           /* line */ (const char *) "     .    ",
           /* line */ (const char *) "     .    ",
           /* line */ (const char *) "     .    ",
           /* line */ (const char *) "   ......^",
           /* line */ (const char *) " ...m.g.  ",
           /* line */ (const char *) " .|.....  ",
           /* line */ (const char *) " ....xx.  ",
           /* line */ (const char *) "^....xx.  ",
           /* line */ (const char *) "   .....  ",
           /* line */ (const char *) "      ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "              ^        ",
           /* line */ (const char *) "    .................  ",
           /* line */ (const char *) "^............g.m.m....^",
           /* line */ (const char *) "           .........   ",
           /* line */ (const char *) "                  ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^            ",
           /* line */ (const char *) "^................   ",
           /* line */ (const char *) "  ...g.g.....m.....^",
           /* line */ (const char *) "  .|.....g.m...m.   ",
           /* line */ (const char *) "  ...............   ",
           /* line */ (const char *) "  .                 ",
           /* line */ (const char *) "  ^                 ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^     ",
           /* line */ (const char *) "     .....  ",
           /* line */ (const char *) "     .....  ",
           /* line */ (const char *) "^.......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ..........^",
           /* line */ (const char *) "     .....  ",
           /* line */ (const char *) "       ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) "     ..... ",
           /* line */ (const char *) "     ..CC.^",
           /* line */ (const char *) "^.....CCC. ",
           /* line */ (const char *) " .....CCm. ",
           /* line */ (const char *) "     ..... ",
           /* line */ (const char *) "        ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^       ",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) "^....x..^",
           /* line */ (const char *) " ..G...x ",
           /* line */ (const char *) " .....xx ",
           /* line */ (const char *) "     ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^       ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "^.g.m.m..|..^",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "  ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) "    .....  ",
           /* line */ (const char *) " .....m... ",
           /* line */ (const char *) "^..m....m.^",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^       ",
           /* line */ (const char *) "    .....       ",
           /* line */ (const char *) "^......x.....   ",
           /* line */ (const char *) "    x....m.G...^",
           /* line */ (const char *) "    xx.......   ",
           /* line */ (const char *) "           .    ",
           /* line */ (const char *) "           ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^    ",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) "^...x..G.~~... ",
           /* line */ (const char *) " CC......~~~.. ",
           /* line */ (const char *) "..C......m~~..^",
           /* line */ (const char *) "m.      .....  ",
           /* line */ (const char *) " ^             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^     ",
           /* line */ (const char *) "   ........^",
           /* line */ (const char *) " ...xCx.... ",
           /* line */ (const char *) " ...C|C.x.. ",
           /* line */ (const char *) "^.m.xCx...x ",
           /* line */ (const char *) " ........xx ",
           /* line */ (const char *) "        ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "              ^    ",
           /* line */ (const char *) "        .......    ",
           /* line */ (const char *) "        ..xxx..    ",
           /* line */ (const char *) "        ..xxx..    ",
           /* line */ (const char *) "^.........xxx.....^",
           /* line */ (const char *) " ..m.x.m......g.|. ",
           /* line */ (const char *) " ................. ",
           /* line */ (const char *) "    ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) " ...xxx.. ",
           /* line */ (const char *) " .g.Dmx..^",
           /* line */ (const char *) "^...xxx.. ",
           /* line */ (const char *) " ........ ",
           /* line */ (const char *) "       ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^       ",
           /* line */ (const char *) "           .....     ",
           /* line */ (const char *) "           .....     ",
           /* line */ (const char *) "  ..........vvv....  ",
           /* line */ (const char *) "^..|..x.x.g.sMv.g...^",
           /* line */ (const char *) "  ..........vvv....  ",
           /* line */ (const char *) "           .....     ",
           /* line */ (const char *) "            ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "^...........^",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "  ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^     ",
           /* line */ (const char *) " ......   ",
           /* line */ (const char *) "^........ ",
           /* line */ (const char *) "..M.m.x..^",
           /* line */ (const char *) "......... ",
           /* line */ (const char *) "m.  ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^       ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "   ..xxx.. ",
           /* line */ (const char *) " ....xxx..^",
           /* line */ (const char *) "^.g..xxx.. ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "    ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "      .       ",
           /* line */ (const char *) "      .       ",
           /* line */ (const char *) " .......      ",
           /* line */ (const char *) "^...........  ",
           /* line */ (const char *) " ............^",
           /* line */ (const char *) " ...........  ",
           /* line */ (const char *) "   .........  ",
           /* line */ (const char *) "   .          ",
           /* line */ (const char *) "   ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^      ",
           /* line */ (const char *) "  ............... ",
           /* line */ (const char *) "  ....g..m.xxx... ",
           /* line */ (const char *) "^..x.......x...g. ",
           /* line */ (const char *) "  .........xxx...^",
           /* line */ (const char *) "         ......   ",
           /* line */ (const char *) "              ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^  ",
           /* line */ (const char *) "    ....... ",
           /* line */ (const char *) "    ....M..^",
           /* line */ (const char *) " ....x..... ",
           /* line */ (const char *) " ..m...m... ",
           /* line */ (const char *) "^....g...```",
           /* line */ (const char *) "    ....````",
           /* line */ (const char *) "      ^   `m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^            ",
           /* line */ (const char *) "  ...................^",
           /* line */ (const char *) "^..x.|.m..x..g.m..    ",
           /* line */ (const char *) "  ................    ",
           /* line */ (const char *) "          ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^          ",
           /* line */ (const char *) "^...m......^",
           /* line */ (const char *) " `......... ",
           /* line */ (const char *) " ``.g.|..xx ",
           /* line */ (const char *) "```.....xxx ",
           /* line */ (const char *) "$``    .xxx ",
           /* line */ (const char *) "       ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "              ^     ",
           /* line */ (const char *) "         ......     ",
           /* line */ (const char *) "^..........m....... ",
           /* line */ (const char *) " ............x.....^",
           /* line */ (const char *) "         ......     ",
           /* line */ (const char *) "            ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^      ",
           /* line */ (const char *) "     .......... ",
           /* line */ (const char *) "^........xCx... ",
           /* line */ (const char *) ".......g.C|C.|. ",
           /* line */ (const char *) "..|.G....xCx... ",
           /* line */ (const char *) "......|......m.^",
           /* line */ (const char *) ".... .......... ",
           /* line */ (const char *) "           ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^   ",
           /* line */ (const char *) " ..............^",
           /* line */ (const char *) "^.g.g.M.x.m.|.. ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "          ...   ",
           /* line */ (const char *) "           ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^       ",
           /* line */ (const char *) "         .       ",
           /* line */ (const char *) "         ....... ",
           /* line */ (const char *) "         .x.xDx. ",
           /* line */ (const char *) "^...........xmx.^",
           /* line */ (const char *) "  .|..g.m.x.xxx. ",
           /* line */ (const char *) "  .............. ",
           /* line */ (const char *) "  ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^         ",
           /* line */ (const char *) "            .         ",
           /* line */ (const char *) "            ...       ",
           /* line */ (const char *) " ..................   ",
           /* line */ (const char *) " ..................   ",
           /* line */ (const char *) " ..................   ",
           /* line */ (const char *) "^....................^",
           /* line */ (const char *) "            ...       ",
           /* line */ (const char *) "            ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) "       ... ",
           /* line */ (const char *) "        ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^       ",
           /* line */ (const char *) "         .       ",
           /* line */ (const char *) "         .       ",
           /* line */ (const char *) "        ......   ",
           /* line */ (const char *) "        ..~...   ",
           /* line */ (const char *) "   ......x~x...  ",
           /* line */ (const char *) "^.......~~|~~...^",
           /* line */ (const char *) "  ..|..x.x~x...  ",
           /* line */ (const char *) "  ........~....  ",
           /* line */ (const char *) "  m.       ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^    ",
           /* line */ (const char *) "       ....   ",
           /* line */ (const char *) "       .|..   ",
           /* line */ (const char *) "       ....   ",
           /* line */ (const char *) "    .....|..  ",
           /* line */ (const char *) "^....x.x.....^",
           /* line */ (const char *) "    ........  ",
           /* line */ (const char *) "       ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " m`` ^        ",
           /* line */ (const char *) " ```........  ",
           /* line */ (const char *) "  ``......x..^",
           /* line */ (const char *) "  `...x..m..  ",
           /* line */ (const char *) "^.......x...  ",
           /* line */ (const char *) "    ........  ",
           /* line */ (const char *) "          .   ",
           /* line */ (const char *) "          .   ",
           /* line */ (const char *) "          ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                 ^     ",
           /* line */ (const char *) "                 .     ",
           /* line */ (const char *) "         ..........    ",
           /* line */ (const char *) "^..........xxx.|.x...  ",
           /* line */ (const char *) "   xx..m.....x.....g.  ",
           /* line */ (const char *) "   xxx...x.xxx..m.....^",
           /* line */ (const char *) "   xxx...............  ",
           /* line */ (const char *) "                 ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^     ",
           /* line */ (const char *) "          ...   ",
           /* line */ (const char *) " ..........m... ",
           /* line */ (const char *) " ...g.......... ",
           /* line */ (const char *) " .g...m.G.m..|.^",
           /* line */ (const char *) "^.............. ",
           /* line */ (const char *) "          ...   ",
           /* line */ (const char *) "           ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                 ^  .m",
           /* line */ (const char *) "   ................C..",
           /* line */ (const char *) "^...x.......xxx.g..CC ",
           /* line */ (const char *) "   ...x.g.g.Dmx......^",
           /* line */ (const char *) "   .........xxx...... ",
           /* line */ (const char *) "          ......      ",
           /* line */ (const char *) "            .         ",
           /* line */ (const char *) "            ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^   ",
           /* line */ (const char *) "^...........xx ",
           /* line */ (const char *) " ..x.........x ",
           /* line */ (const char *) " x....g.G..x.. ",
           /* line */ (const char *) " xx...........^",
           /* line */ (const char *) "       ....    ",
           /* line */ (const char *) "       ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^      ",
           /* line */ (const char *) "  .......     ",
           /* line */ (const char *) "^..xxx.......^",
           /* line */ (const char *) "  .xg..g.g... ",
           /* line */ (const char *) "  .x.......```",
           /* line */ (const char *) "  ........````",
           /* line */ (const char *) "       .    `m",
           /* line */ (const char *) "       .      ",
           /* line */ (const char *) "       ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^        ",
           /* line */ (const char *) "      .......... ",
           /* line */ (const char *) "      ..g.g..... ",
           /* line */ (const char *) "^...........xxx. ",
           /* line */ (const char *) " ..m.|....|.x...^",
           /* line */ (const char *) " .......x...x..x ",
           /* line */ (const char *) "      ........xx ",
           /* line */ (const char *) "            ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^    ",
           /* line */ (const char *) " .....   ",
           /* line */ (const char *) "^.M.m... ",
           /* line */ (const char *) " .....|.^",
           /* line */ (const char *) "     ... ",
           /* line */ (const char *) "     ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^            ",
           /* line */ (const char *) "     .........    ",
           /* line */ (const char *) "     ............^",
           /* line */ (const char *) " .............    ",
           /* line */ (const char *) " .............    ",
           /* line */ (const char *) "^.............    ",
           /* line */ (const char *) "     .........    ",
           /* line */ (const char *) "        ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^       ",
           /* line */ (const char *) "  ........^",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "^..g.x..x. ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "      .    ",
           /* line */ (const char *) "      .    ",
           /* line */ (const char *) "      ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^   ",
           /* line */ (const char *) "     ~~  .....  ",
           /* line */ (const char *) "    ~~   .|.m.  ",
           /* line */ (const char *) "    ~ ~  .....  ",
           /* line */ (const char *) "         .g.G.  ",
           /* line */ (const char *) "^..............^",
           /* line */ (const char *) "  ............. ",
           /* line */ (const char *) "           .    ",
           /* line */ (const char *) "           ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^     ",
           /* line */ (const char *) "        .     ",
           /* line */ (const char *) "    .......   ",
           /* line */ (const char *) "    .......   ",
           /* line */ (const char *) "    .......   ",
           /* line */ (const char *) "    .......   ",
           /* line */ (const char *) "^............^",
           /* line */ (const char *) " ...........  ",
           /* line */ (const char *) "    ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^         ",
           /* line */ (const char *) "^.......... ",
           /* line */ (const char *) " ..........^",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^     ",
           /* line */ (const char *) "      ........... ",
           /* line */ (const char *) "      .xCx.xxx...^",
           /* line */ (const char *) " ......C|C.xxx.g. ",
           /* line */ (const char *) "^..|.g.xCx.xxx... ",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) " ^                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^       ",
           /* line */ (const char *) "^.............^",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) "         ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^    ",
           /* line */ (const char *) "  .....^",
           /* line */ (const char *) "  ..... ",
           /* line */ (const char *) "^...... ",
           /* line */ (const char *) " ...... ",
           /* line */ (const char *) "    ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "    ...... ",
           /* line */ (const char *) "    ...... ",
           /* line */ (const char *) "    ...... ",
           /* line */ (const char *) " .........^",
           /* line */ (const char *) "^......... ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) " ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^     ",
           /* line */ (const char *) "        ...   ",
           /* line */ (const char *) "        ...   ",
           /* line */ (const char *) " ........|...^",
           /* line */ (const char *) "^.m.g..|...x. ",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "       ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^                ",
           /* line */ (const char *) "       .                ",
           /* line */ (const char *) "       .                ",
           /* line */ (const char *) "      ...........       ",
           /* line */ (const char *) "^.......|...x.x........^",
           /* line */ (const char *) " .|.m.|...x.....m.x.    ",
           /* line */ (const char *) " ...................    ",
           /* line */ (const char *) "         .              ",
           /* line */ (const char *) "         ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^     ",
           /* line */ (const char *) "     ........ ",
           /* line */ (const char *) " ............^",
           /* line */ (const char *) "^............ ",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "     ........ ",
           /* line */ (const char *) "           ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^             ",
           /* line */ (const char *) "^................     ",
           /* line */ (const char *) " ..M..x.|...g.m......^",
           /* line */ (const char *) " .........g......     ",
           /* line */ (const char *) "         ....         ",
           /* line */ (const char *) "           ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^  ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "^.m..g.m.x..m..^",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "          ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^        ",
           /* line */ (const char *) " .......xxx ",
           /* line */ (const char *) " .......xxx ",
           /* line */ (const char *) "^.vvv.x..xx ",
           /* line */ (const char *) " .sTv...... ",
           /* line */ (const char *) " .vvv..x.x.^",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^             ",
           /* line */ (const char *) " ..............^",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "^.............. ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "   ^            ",
           /* end */ nullptr);
}
