//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_charmap.hpp"
#include "my_level.hpp"

// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// 100 rooms of type 'cross' from seed 'maniac'
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
// AUTOGENERATED FILE
//
void rooms_cross(Gamep g)
{
  TRACE();

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                ^   ",
           /* line */ (const char *) "^.................. ",
           /* line */ (const char *) " .................. ",
           /* line */ (const char *) " ..................^",
           /* line */ (const char *) "          ......    ",
           /* line */ (const char *) "             ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^       ",
           /* line */ (const char *) "    ........... ",
           /* line */ (const char *) "^.....x.g.m..g.^",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "           ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^        ",
           /* line */ (const char *) " xx........ ",
           /* line */ (const char *) " x.......x.^",
           /* line */ (const char *) " ..x.g.|... ",
           /* line */ (const char *) "^........g. ",
           /* line */ (const char *) "     ...... ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^     ",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) " .m..m........|.. ",
           /* line */ (const char *) "^......g.m.G.....^",
           /* line */ (const char *) "      ..........  ",
           /* line */ (const char *) "      ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ^   ",
           /* line */ (const char *) " ................  ",
           /* line */ (const char *) "^..x.g.|...x...m..^",
           /* line */ (const char *) " x.......g...x...  ",
           /* line */ (const char *) " xx..............  ",
           /* line */ (const char *) "          ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^    ",
           /* line */ (const char *) "       .    ",
           /* line */ (const char *) "    ......  ",
           /* line */ (const char *) "^.........  ",
           /* line */ (const char *) "    .......^",
           /* line */ (const char *) "    ......  ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) " xx........... ",
           /* line */ (const char *) " x....x.x.m.g. ",
           /* line */ (const char *) "^..x..........^",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) "            ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^   ",
           /* line */ (const char *) "          .   ",
           /* line */ (const char *) "      .....   ",
           /* line */ (const char *) "      .xxx.   ",
           /* line */ (const char *) "      .sTx.   ",
           /* line */ (const char *) "^......xxx..  ",
           /* line */ (const char *) "  .|.x.......^",
           /* line */ (const char *) "  ..........  ",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^      ",
           /* line */ (const char *) "   .      ",
           /* line */ (const char *) "   ...... ",
           /* line */ (const char *) "^...m..G.^",
           /* line */ (const char *) "   ...... ",
           /* line */ (const char *) "   .      ",
           /* line */ (const char *) "   ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ^     ",
           /* line */ (const char *) "^...................^",
           /* line */ (const char *) " ..g.|.|.x.g.m..g.g. ",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "         ......      ",
           /* line */ (const char *) "            ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^     ",
           /* line */ (const char *) "         ....     ",
           /* line */ (const char *) "         ..x.     ",
           /* line */ (const char *) "         ....     ",
           /* line */ (const char *) "^.........|......^",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "             ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^      ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " .g..m....g. ",
           /* line */ (const char *) "^......x....^",
           /* line */ (const char *) " ............",
           /* line */ (const char *) "         ^ .m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^   ",
           /* line */ (const char *) "        ....... ",
           /* line */ (const char *) "^..............^",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "        ....... ",
           /* line */ (const char *) "             ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "              ^  ",
           /* line */ (const char *) "              .  ",
           /* line */ (const char *) "        .......  ",
           /* line */ (const char *) "  ..............^",
           /* line */ (const char *) "^............... ",
           /* line */ (const char *) "  .............. ",
           /* line */ (const char *) "  .............. ",
           /* line */ (const char *) "        ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "m.        ^    ",
           /* line */ (const char *) ".............. ",
           /* line */ (const char *) " .|.....x.xsx.^",
           /* line */ (const char *) "^...|..x..x$x. ",
           /* line */ (const char *) " .....x...xxx..",
           /* line */ (const char *) "    ...........",
           /* line */ (const char *) "          ^  .m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^               ",
           /* line */ (const char *) "^...................  ",
           /* line */ (const char *) "  .x.g..M.g.........  ",
           /* line */ (const char *) "  ...........|.g.|...^",
           /* line */ (const char *) "         ..........   ",
           /* line */ (const char *) "          .           ",
           /* line */ (const char *) "          ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "$`` ^        ",
           /* line */ (const char *) "```......... ",
           /* line */ (const char *) " ``.|.x..xx. ",
           /* line */ (const char *) " `.......xx.^",
           /* line */ (const char *) "^...m....... ",
           /* line */ (const char *) "        ...  ",
           /* line */ (const char *) "         ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^             ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) "  .x..|.g..|.    ",
           /* line */ (const char *) "  ...........    ",
           /* line */ (const char *) "         .       ",
           /* line */ (const char *) "         .       ",
           /* line */ (const char *) "         ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^       ",
           /* line */ (const char *) "^.............. ",
           /* line */ (const char *) " ....x..g..g.x.^",
           /* line */ (const char *) "    ........... ",
           /* line */ (const char *) "             ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^            ",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) " ..........x.. ",
           /* line */ (const char *) " ..m.x..m.xxx. ",
           /* line */ (const char *) "^..........x..^",
           /* line */ (const char *) "    .......... ",
           /* line */ (const char *) "           ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^        .m ",
           /* line */ (const char *) "       ........... ",
           /* line */ (const char *) "       .xxx.m..... ",
           /* line */ (const char *) "  ......xxx...g...^",
           /* line */ (const char *) "^.......xxx.x....  ",
           /* line */ (const char *) "       ..........  ",
           /* line */ (const char *) "        ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^    ",
           /* line */ (const char *) "^........... ",
           /* line */ (const char *) "  xx......g.^",
           /* line */ (const char *) "  xxx..m.... ",
           /* line */ (const char *) "  xxx....... ",
           /* line */ (const char *) "       ...   ",
           /* line */ (const char *) "         .   ",
           /* line */ (const char *) "         ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "$.           ^   ",
           /* line */ (const char *) "..|...........xx ",
           /* line */ (const char *) " |..x......|...x ",
           /* line */ (const char *) " .....|.x....x..^",
           /* line */ (const char *) "^.........m..... ",
           /* line */ (const char *) "         .....   ",
           /* line */ (const char *) "             ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) "^.........  ",
           /* line */ (const char *) " `..x.x.m.  ",
           /* line */ (const char *) " ``........^",
           /* line */ (const char *) "```...|.|.. ",
           /* line */ (const char *) "C``  ...... ",
           /* line */ (const char *) "       ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^    ",
           /* line */ (const char *) " .............^",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) "^............. ",
           /* line */ (const char *) "    .........  ",
           /* line */ (const char *) "    ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^      ",
           /* line */ (const char *) "           ...      ",
           /* line */ (const char *) "           ...      ",
           /* line */ (const char *) "           .m.      ",
           /* line */ (const char *) "^.................. ",
           /* line */ (const char *) " ...........|......^",
           /* line */ (const char *) "           ...      ",
           /* line */ (const char *) "             ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^   ",
           /* line */ (const char *) "           .   ",
           /* line */ (const char *) "        ....   ",
           /* line */ (const char *) "        ..g.   ",
           /* line */ (const char *) "        ....   ",
           /* line */ (const char *) "^.........x...^",
           /* line */ (const char *) "  ............ ",
           /* line */ (const char *) "       ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^  ",
           /* line */ (const char *) "^.......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ..........^",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) "        ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^     ",
           /* line */ (const char *) "          .....   ",
           /* line */ (const char *) "          .....   ",
           /* line */ (const char *) "          .....   ",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "^................^",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "               ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^         ",
           /* line */ (const char *) "       .....     ",
           /* line */ (const char *) "       .....     ",
           /* line */ (const char *) "       .m.x.     ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) " .x.g.g.m..m..|. ",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) "     ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^      ",
           /* line */ (const char *) "     .............  ",
           /* line */ (const char *) "^.....m...g.......  ",
           /* line */ (const char *) "     ...|....g..m..^",
           /* line */ (const char *) "       ............ ",
           /* line */ (const char *) "         ^       .m ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^        ",
           /* line */ (const char *) "        ....     ",
           /* line */ (const char *) "        .|..     ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) "  .............  ",
           /* line */ (const char *) "     .           ",
           /* line */ (const char *) "     ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^   ",
           /* line */ (const char *) " ..........^",
           /* line */ (const char *) "^....xxx.x. ",
           /* line */ (const char *) " ..x..xx... ",
           /* line */ (const char *) " x.....x.x. ",
           /* line */ (const char *) " xx........ ",
           /* line */ (const char *) "    ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^     ",
           /* line */ (const char *) "            .     ",
           /* line */ (const char *) "         ....     ",
           /* line */ (const char *) "         ....     ",
           /* line */ (const char *) "  ...............^",
           /* line */ (const char *) "  ............... ",
           /* line */ (const char *) "^................ ",
           /* line */ (const char *) "  ............... ",
           /* line */ (const char *) "              ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "$.      ^    ",
           /* line */ (const char *) "..|......... ",
           /* line */ (const char *) " |.....m....^",
           /* line */ (const char *) "^....x...m.. ",
           /* line */ (const char *) " .x...x..... ",
           /* line */ (const char *) "....g..x.x.. ",
           /* line */ (const char *) "............ ",
           /* line */ (const char *) "m.      ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^            ",
           /* line */ (const char *) "^............. ",
           /* line */ (const char *) " .g.m.x..m..|. ",
           /* line */ (const char *) " .............^",
           /* line */ (const char *) "      ......   ",
           /* line */ (const char *) "       ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "      .       ",
           /* line */ (const char *) "     .....    ",
           /* line */ (const char *) "^.....LLm....^",
           /* line */ (const char *) " ...x.LLL.|.  ",
           /* line */ (const char *) " .g....LL...  ",
           /* line */ (const char *) " ...........  ",
           /* line */ (const char *) "        ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^           ",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) " ..|.g..|.xx. ",
           /* line */ (const char *) "^.........xx.^",
           /* line */ (const char *) "     ........ ",
           /* line */ (const char *) "        ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^  ",
           /* line */ (const char *) "^.......^",
           /* line */ (const char *) " .x...|. ",
           /* line */ (const char *) " ...|... ",
           /* line */ (const char *) " ....... ",
           /* line */ (const char *) "     ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^       ",
           /* line */ (const char *) "        .........   ",
           /* line */ (const char *) "        .........   ",
           /* line */ (const char *) "        .........   ",
           /* line */ (const char *) "^..................^",
           /* line */ (const char *) "   ...............  ",
           /* line */ (const char *) "   ^                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^       ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " .m..x...... ",
           /* line */ (const char *) "^....xg..m.. ",
           /* line */ (const char *) " ....xxx....^",
           /* line */ (const char *) "    .......  ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^     ",
           /* line */ (const char *) " ...............^",
           /* line */ (const char *) "^.........g....  ",
           /* line */ (const char *) "         ...     ",
           /* line */ (const char *) "           ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^     ",
           /* line */ (const char *) "        ....     ",
           /* line */ (const char *) "        ....     ",
           /* line */ (const char *) " ...............^",
           /* line */ (const char *) "^............... ",
           /* line */ (const char *) "        ....     ",
           /* line */ (const char *) "           ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^         ",
           /* line */ (const char *) "    .............    ",
           /* line */ (const char *) "^....m.g.m.g.|.|....^",
           /* line */ (const char *) "    .............    ",
           /* line */ (const char *) "         ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^       ",
           /* line */ (const char *) "     ...........  ",
           /* line */ (const char *) "  ...............^",
           /* line */ (const char *) "^...............  ",
           /* line */ (const char *) "     ...........  ",
           /* line */ (const char *) "           ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^          ",
           /* line */ (const char *) "       ........      ",
           /* line */ (const char *) "       .m.m.|..      ",
           /* line */ (const char *) "  ...............    ",
           /* line */ (const char *) "^........x.m.g......^",
           /* line */ (const char *) "       ........      ",
           /* line */ (const char *) "         ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "     ........^",
           /* line */ (const char *) "     .|.g.... ",
           /* line */ (const char *) " .........x.. ",
           /* line */ (const char *) " .|.x.......` ",
           /* line */ (const char *) "^.....x..x.`` ",
           /* line */ (const char *) "     ......```",
           /* line */ (const char *) "          ^``C",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^          ",
           /* line */ (const char *) "       .........  ",
           /* line */ (const char *) "       .x...xxx.  ",
           /* line */ (const char *) "       ..x..s$x.  ",
           /* line */ (const char *) "^.........x.xxx..^",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) "      ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                 ^     ",
           /* line */ (const char *) "                 .     ",
           /* line */ (const char *) "^......m.............. ",
           /* line */ (const char *) "    ......x........xx.^",
           /* line */ (const char *) "   ```..g....|.m.x.xx. ",
           /* line */ (const char *) "   ````............... ",
           /* line */ (const char *) "   $`           ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  m``          ^        ",
           /* line */ (const char *) "  ```...............xx  ",
           /* line */ (const char *) "   ``.m....g.g.CCC...x  ",
           /* line */ (const char *) "   `.....|.....C$C.x..  ",
           /* line */ (const char *) "^...........|..CCC.....^",
           /* line */ (const char *) "          ...........   ",
           /* line */ (const char *) "                 ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^    ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......x..^",
           /* line */ (const char *) " .m..x..... ",
           /* line */ (const char *) " ...m...|.. ",
           /* line */ (const char *) "^..x..M.... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                ^  ",
           /* line */ (const char *) "^.................^",
           /* line */ (const char *) " ........|.m.x.... ",
           /* line */ (const char *) "       .........   ",
           /* line */ (const char *) "         ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^         ",
           /* line */ (const char *) "   .........xx ",
           /* line */ (const char *) "   .x...|.x..x ",
           /* line */ (const char *) "   ...m...x... ",
           /* line */ (const char *) "   .......xxx.^",
           /* line */ (const char *) "^...|.x.m..... ",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) "           ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^  ",
           /* line */ (const char *) "    .........^",
           /* line */ (const char *) " ....xxx.|.m. ",
           /* line */ (const char *) " .g..xxx..... ",
           /* line */ (const char *) "^....xxx.g.m. ",
           /* line */ (const char *) "    ......... ",
           /* line */ (const char *) "    ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^          ",
           /* line */ (const char *) "         ....~..      ",
           /* line */ (const char *) "  xx........x~x......^",
           /* line */ (const char *) "  x....m...~~|~~..xx  ",
           /* line */ (const char *) "^...x....x..x~x..xxx  ",
           /* line */ (const char *) "  ...........~...xxx  ",
           /* line */ (const char *) "         .......      ",
           /* line */ (const char *) "         ^            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^   ",
           /* line */ (const char *) "    ......^",
           /* line */ (const char *) " ........  ",
           /* line */ (const char *) " ........  ",
           /* line */ (const char *) "^........  ",
           /* line */ (const char *) " ........  ",
           /* line */ (const char *) "   ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^      ",
           /* line */ (const char *) " ................  ",
           /* line */ (const char *) " ..x....m.....xx.  ",
           /* line */ (const char *) " .....x...x.g.xx..^",
           /* line */ (const char *) "^................  ",
           /* line */ (const char *) "          ...      ",
           /* line */ (const char *) "            .      ",
           /* line */ (const char *) "            ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "              ^         ",
           /* line */ (const char *) "            ...         ",
           /* line */ (const char *) "^......................^",
           /* line */ (const char *) "  .m.m.x..x.g.|.m.m.    ",
           /* line */ (const char *) "  ..................    ",
           /* line */ (const char *) "            ...         ",
           /* line */ (const char *) "             ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^    ",
           /* line */ (const char *) "     .....   ",
           /* line */ (const char *) "     ..xx.   ",
           /* line */ (const char *) "     ..xx.   ",
           /* line */ (const char *) " .........   ",
           /* line */ (const char *) "^.m..x.M....^",
           /* line */ (const char *) " .........   ",
           /* line */ (const char *) " .           ",
           /* line */ (const char *) " .           ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^ .m",
           /* line */ (const char *) " ..............",
           /* line */ (const char *) " ..|..|.|......",
           /* line */ (const char *) "^..........g..^",
           /* line */ (const char *) " ............. ",
           /* line */ (const char *) "   ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "     ...  ",
           /* line */ (const char *) "     .|.  ",
           /* line */ (const char *) "^........^",
           /* line */ (const char *) "  ....|.  ",
           /* line */ (const char *) "     ...  ",
           /* line */ (const char *) "      .   ",
           /* line */ (const char *) "      .   ",
           /* line */ (const char *) "      ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^     ",
           /* line */ (const char *) " ........xx ",
           /* line */ (const char *) "^.g.|.....x ",
           /* line */ (const char *) " .....g.x..^",
           /* line */ (const char *) "    ....... ",
           /* line */ (const char *) "       ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^                ",
           /* line */ (const char *) "^.................. ",
           /* line */ (const char *) " ..x.m.....G.x.....^",
           /* line */ (const char *) " ......x.x.....m..x ",
           /* line */ (const char *) " ................xx ",
           /* line */ (const char *) "  ^                 ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^          ",
           /* line */ (const char *) "    .......... ",
           /* line */ (const char *) "    .......... ",
           /* line */ (const char *) "    .......... ",
           /* line */ (const char *) "^............. ",
           /* line */ (const char *) " .............^",
           /* line */ (const char *) "    .......... ",
           /* line */ (const char *) "     ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "         .   ",
           /* line */ (const char *) "         .   ",
           /* line */ (const char *) "        ...  ",
           /* line */ (const char *) "^........m..^",
           /* line */ (const char *) "    .......  ",
           /* line */ (const char *) "       ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^            ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) "  ............   ",
           /* line */ (const char *) "  ............   ",
           /* line */ (const char *) "         .       ",
           /* line */ (const char *) "         ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ^      ",
           /* line */ (const char *) "     ..........    ",
           /* line */ (const char *) " .....mLL..|...... ",
           /* line */ (const char *) " .g.m.LLL.....x.x. ",
           /* line */ (const char *) "^.....LL..m.g.....^",
           /* line */ (const char *) "     ..........    ",
           /* line */ (const char *) "            ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^       ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) " ..x...x.... ",
           /* line */ (const char *) " ..xxx...x..^",
           /* line */ (const char *) "^....x.m...x ",
           /* line */ (const char *) " .........xx ",
           /* line */ (const char *) "    ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                ^    ",
           /* line */ (const char *) "       ..........    ",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "^...................^",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "              ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^    ",
           /* line */ (const char *) "      ...  ",
           /* line */ (const char *) "^......x..^",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "    ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                ^      ",
           /* line */ (const char *) "            .......    ",
           /* line */ (const char *) "            .G..|..    ",
           /* line */ (const char *) "            .......    ",
           /* line */ (const char *) "    ..................^",
           /* line */ (const char *) "^.....x.x..x..g.x.g.m. ",
           /* line */ (const char *) "    .................. ",
           /* line */ (const char *) "         ^             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^            ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) " .x.....g.x.m.   ",
           /* line */ (const char *) " ...|.g.......   ",
           /* line */ (const char *) " ........m....   ",
           /* line */ (const char *) "       ....      ",
           /* line */ (const char *) "         ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^         `$",
           /* line */ (const char *) " ........````",
           /* line */ (const char *) "^.|..|.G..```",
           /* line */ (const char *) " ...........^",
           /* line */ (const char *) "    ....m... ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^             ",
           /* line */ (const char *) "^..............^",
           /* line */ (const char *) "  xx...G.x..xx. ",
           /* line */ (const char *) "  xxx.......xx. ",
           /* line */ (const char *) "  xxx....|..... ",
           /* line */ (const char *) "        .....   ",
           /* line */ (const char *) "         .      ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^         ",
           /* line */ (const char *) "    .         ",
           /* line */ (const char *) "   ..........^",
           /* line */ (const char *) "^...x.|....m. ",
           /* line */ (const char *) "   ......G....",
           /* line */ (const char *) "     .........",
           /* line */ (const char *) "          . .m",
           /* line */ (const char *) "          ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^    ",
           /* line */ (const char *) "  .......    ",
           /* line */ (const char *) " ...x.x.....^",
           /* line */ (const char *) "^.g.....x.g. ",
           /* line */ (const char *) " ........... ",
           /* line */ (const char *) "        ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ^       ",
           /* line */ (const char *) "  ...................  ",
           /* line */ (const char *) "^....|......xxx.g.g...^",
           /* line */ (const char *) "  .m....m.x.xm......x  ",
           /* line */ (const char *) "  ..........x..m...xx  ",
           /* line */ (const char *) "          .......      ",
           /* line */ (const char *) "              ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^       ",
           /* line */ (const char *) "      ......  ",
           /* line */ (const char *) "^.......g.g..^",
           /* line */ (const char *) " ............ ",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^        ",
           /* line */ (const char *) "  .        ",
           /* line */ (const char *) "^........  ",
           /* line */ (const char *) "  ..m..m..^",
           /* line */ (const char *) "   ......  ",
           /* line */ (const char *) "     .     ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^         ",
           /* line */ (const char *) "          .         ",
           /* line */ (const char *) "     ...........    ",
           /* line */ (const char *) "^.....g..x.|..m....^",
           /* line */ (const char *) "  ..............    ",
           /* line */ (const char *) "          ^         ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^       ",
           /* line */ (const char *) "          ....       ",
           /* line */ (const char *) "          ....       ",
           /* line */ (const char *) "^..........G........^",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "          ....       ",
           /* line */ (const char *) "          ^          ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^        ",
           /* line */ (const char *) "       ....      ",
           /* line */ (const char *) "       ....      ",
           /* line */ (const char *) "       ....      ",
           /* line */ (const char *) "^...............^",
           /* line */ (const char *) " ............... ",
           /* line */ (const char *) "            ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^      ",
           /* line */ (const char *) "     .      ",
           /* line */ (const char *) " ..........^",
           /* line */ (const char *) "^.........  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "    ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ^        ",
           /* line */ (const char *) "         ........     ",
           /* line */ (const char *) "  xxx...............  ",
           /* line */ (const char *) "  xxx.g...LLm..|.g..  ",
           /* line */ (const char *) "  xx....x.LLL.......  ",
           /* line */ (const char *) "^..........LL..g.....^",
           /* line */ (const char *) "         ........     ",
           /* line */ (const char *) "               ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^          ",
           /* line */ (const char *) " xx........    ",
           /* line */ (const char *) " x...xsx......^",
           /* line */ (const char *) "^..x.x$x..g... ",
           /* line */ (const char *) " ....xxx....m. ",
           /* line */ (const char *) "    .......... ",
           /* line */ (const char *) "            ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^          ",
           /* line */ (const char *) "          .          ",
           /* line */ (const char *) "        .........    ",
           /* line */ (const char *) "        ..g.|.m..    ",
           /* line */ (const char *) "^................... ",
           /* line */ (const char *) " .g.G.x.m.|..g..g.g.^",
           /* line */ (const char *) " ................... ",
           /* line */ (const char *) "      ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^             ",
           /* line */ (const char *) " ..............^",
           /* line */ (const char *) "^.............. ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) " .............. ",
           /* line */ (const char *) "    ........... ",
           /* line */ (const char *) "    ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^        ",
           /* line */ (const char *) "      .........^",
           /* line */ (const char *) " ......xxx.x..  ",
           /* line */ (const char *) "^.m.m..xxx....  ",
           /* line */ (const char *) " ......xxx...|  ",
           /* line */ (const char *) "      ......|.. ",
           /* line */ (const char *) "         .   .$ ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "                ^     ",
           /* line */ (const char *) "^...................  ",
           /* line */ (const char *) "  ........m.|..x.....^",
           /* line */ (const char *) "         ........     ",
           /* line */ (const char *) "              .       ",
           /* line */ (const char *) "              ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^            ",
           /* line */ (const char *) "^...................^",
           /* line */ (const char *) " .......|..m.m.m.... ",
           /* line */ (const char *) "       ..........    ",
           /* line */ (const char *) "       ^             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^  ",
           /* line */ (const char *) "           .  ",
           /* line */ (const char *) "      ....... ",
           /* line */ (const char *) "      .xxx.x. ",
           /* line */ (const char *) "      ..gx...^",
           /* line */ (const char *) "^........x.|. ",
           /* line */ (const char *) " ......m..... ",
           /* line */ (const char *) "      ........",
           /* line */ (const char *) "           ^.m",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^       ",
           /* line */ (const char *) "        .........  ",
           /* line */ (const char *) "        .xsx.x.|.  ",
           /* line */ (const char *) "        .xmx.....  ",
           /* line */ (const char *) " ........xxx.|.|..^",
           /* line */ (const char *) "^................. ",
           /* line */ (const char *) "        .........  ",
           /* line */ (const char *) "               ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^         ",
           /* line */ (const char *) "        ......    ",
           /* line */ (const char *) "        .LLm..    ",
           /* line */ (const char *) "        .LLL..    ",
           /* line */ (const char *) "^.........LL.....^",
           /* line */ (const char *) " ..m.x.m......g.. ",
           /* line */ (const char *) " ................ ",
           /* line */ (const char *) " ^                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^       ",
           /* line */ (const char *) "   ......  ",
           /* line */ (const char *) " ....|.|.  ",
           /* line */ (const char *) "^.....m...^",
           /* line */ (const char *) "```..|.|.  ",
           /* line */ (const char *) "````.....  ",
           /* line */ (const char *) "C`   ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^   ",
           /* line */ (const char *) "       ....   ",
           /* line */ (const char *) " .......m....^",
           /* line */ (const char *) "^.m.|.x...|.. ",
           /* line */ (const char *) " .......x.... ",
           /* line */ (const char *) "       ....   ",
           /* line */ (const char *) "         ^    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ^            ",
           /* line */ (const char *) "        .........       ",
           /* line */ (const char *) "        .g..x..|.       ",
           /* line */ (const char *) "^..........xxx.........^",
           /* line */ (const char *) "  .......g..x..|.....   ",
           /* line */ (const char *) "        .........       ",
           /* line */ (const char *) "               .        ",
           /* line */ (const char *) "               ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^          ",
           /* line */ (const char *) "        .........   ",
           /* line */ (const char *) "        .g.xxx...   ",
           /* line */ (const char *) "        ...sTx.|.   ",
           /* line */ (const char *) "^........M.xxx.....^",
           /* line */ (const char *) "   ...............  ",
           /* line */ (const char *) "             .      ",
           /* line */ (const char *) "             .      ",
           /* line */ (const char *) "             ^      ",
           /* end */ nullptr);

}
